// <auto-generated />
using System;
using EPManifest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPManifest.Data.Migrations
{
    [DbContext(typeof(EPManifestDbContext))]
    [Migration("20210517022121_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsignorManifest", b =>
                {
                    b.Property<int>("ConsignorsId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestsId")
                        .HasColumnType("int");

                    b.HasKey("ConsignorsId", "ManifestsId");

                    b.HasIndex("ManifestsId");

                    b.ToTable("ConsignorManifest");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1 Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pacific Northwest Freight"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AP Freight"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NM Shipping Inc"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frank's Freight"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pete's Disposal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATI Environmental"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EQ Enviro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Whitehorse Landfill"
                        },
                        new
                        {
                            Id = 5,
                            Name = "YAE"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carmacks Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mayo Health Centre"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whitehorse General Hospital"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Teslin Health Centre"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whistle Bend Place"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShipped")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ConsigneeId");

                    b.ToTable("Manifests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 20, 45, 58, 969, DateTimeKind.Unspecified).AddTicks(7545),
                            DateShipped = new DateTime(2021, 5, 18, 4, 46, 20, 164, DateTimeKind.Unspecified).AddTicks(5165)
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 7, 6, 25, 10, 930, DateTimeKind.Unspecified).AddTicks(7412),
                            DateShipped = new DateTime(2021, 7, 25, 1, 55, 58, 261, DateTimeKind.Unspecified).AddTicks(3560)
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 16, 17, 2, 135, DateTimeKind.Unspecified).AddTicks(4072),
                            DateShipped = new DateTime(2021, 5, 23, 8, 57, 42, 409, DateTimeKind.Unspecified).AddTicks(2103)
                        },
                        new
                        {
                            Id = 4,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 7, 59, 13, 160, DateTimeKind.Unspecified).AddTicks(877),
                            DateShipped = new DateTime(2021, 7, 25, 19, 13, 7, 169, DateTimeKind.Unspecified).AddTicks(8791)
                        },
                        new
                        {
                            Id = 5,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 8, 8, 33, 19, 962, DateTimeKind.Unspecified).AddTicks(6661),
                            DateShipped = new DateTime(2021, 6, 4, 4, 58, 51, 408, DateTimeKind.Unspecified).AddTicks(9233)
                        },
                        new
                        {
                            Id = 6,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 4, 22, 21, 40, 544, DateTimeKind.Unspecified).AddTicks(1668),
                            DateShipped = new DateTime(2021, 8, 2, 10, 27, 32, 445, DateTimeKind.Unspecified).AddTicks(746)
                        },
                        new
                        {
                            Id = 7,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 17, 52, 4, 495, DateTimeKind.Unspecified).AddTicks(8700),
                            DateShipped = new DateTime(2021, 8, 14, 1, 25, 25, 267, DateTimeKind.Unspecified).AddTicks(6764)
                        },
                        new
                        {
                            Id = 8,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 9, 5, 1, 336, DateTimeKind.Unspecified).AddTicks(3007),
                            DateShipped = new DateTime(2021, 6, 11, 5, 18, 46, 977, DateTimeKind.Unspecified).AddTicks(2127)
                        },
                        new
                        {
                            Id = 9,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 3, 1, 10, 11, 227, DateTimeKind.Unspecified).AddTicks(2908),
                            DateShipped = new DateTime(2021, 6, 30, 22, 46, 59, 689, DateTimeKind.Unspecified).AddTicks(4983)
                        },
                        new
                        {
                            Id = 10,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 13, 12, 34, 873, DateTimeKind.Unspecified).AddTicks(8463),
                            DateShipped = new DateTime(2021, 8, 23, 10, 23, 33, 568, DateTimeKind.Unspecified).AddTicks(8002)
                        },
                        new
                        {
                            Id = 11,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 21, 9, 57, 32, 109, DateTimeKind.Unspecified).AddTicks(3953),
                            DateShipped = new DateTime(2021, 5, 27, 3, 30, 3, 635, DateTimeKind.Unspecified).AddTicks(4049)
                        },
                        new
                        {
                            Id = 12,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 10, 6, 11, 852, DateTimeKind.Unspecified).AddTicks(6637),
                            DateShipped = new DateTime(2021, 5, 9, 10, 4, 16, 872, DateTimeKind.Unspecified).AddTicks(6798)
                        },
                        new
                        {
                            Id = 13,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 9, 10, 5, 55, 72, DateTimeKind.Unspecified).AddTicks(4691),
                            DateShipped = new DateTime(2021, 8, 2, 1, 18, 31, 455, DateTimeKind.Unspecified).AddTicks(5575)
                        },
                        new
                        {
                            Id = 14,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 24, 13, 47, 49, 411, DateTimeKind.Unspecified).AddTicks(3620),
                            DateShipped = new DateTime(2021, 6, 13, 18, 9, 41, 356, DateTimeKind.Unspecified).AddTicks(4426)
                        },
                        new
                        {
                            Id = 15,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 6, 59, 14, 796, DateTimeKind.Unspecified).AddTicks(5018),
                            DateShipped = new DateTime(2021, 7, 11, 2, 17, 41, 484, DateTimeKind.Unspecified).AddTicks(9457)
                        },
                        new
                        {
                            Id = 16,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 13, 1, 56, 58, 518, DateTimeKind.Unspecified).AddTicks(4020),
                            DateShipped = new DateTime(2021, 6, 26, 11, 23, 39, 662, DateTimeKind.Unspecified).AddTicks(9417)
                        },
                        new
                        {
                            Id = 17,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 7, 13, 39, 5, 773, DateTimeKind.Unspecified).AddTicks(6468),
                            DateShipped = new DateTime(2021, 7, 24, 1, 33, 31, 183, DateTimeKind.Unspecified).AddTicks(2466)
                        },
                        new
                        {
                            Id = 18,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 11, 8, 24, 12, 770, DateTimeKind.Unspecified).AddTicks(3814),
                            DateShipped = new DateTime(2021, 7, 27, 2, 11, 33, 868, DateTimeKind.Unspecified).AddTicks(6735)
                        },
                        new
                        {
                            Id = 19,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 11, 58, 3, 834, DateTimeKind.Unspecified).AddTicks(5669),
                            DateShipped = new DateTime(2021, 8, 27, 22, 21, 8, 236, DateTimeKind.Unspecified).AddTicks(9994)
                        },
                        new
                        {
                            Id = 20,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 13, 14, 42, 58, 956, DateTimeKind.Unspecified).AddTicks(5184),
                            DateShipped = new DateTime(2021, 6, 15, 2, 6, 40, 336, DateTimeKind.Unspecified).AddTicks(5299)
                        },
                        new
                        {
                            Id = 21,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 19, 3, 33, 54, 853, DateTimeKind.Unspecified).AddTicks(203),
                            DateShipped = new DateTime(2021, 7, 27, 19, 27, 37, 701, DateTimeKind.Unspecified).AddTicks(1062)
                        },
                        new
                        {
                            Id = 22,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 23, 16, 55, 14, 856, DateTimeKind.Unspecified).AddTicks(2253),
                            DateShipped = new DateTime(2021, 6, 20, 18, 45, 22, 853, DateTimeKind.Unspecified).AddTicks(155)
                        },
                        new
                        {
                            Id = 23,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 6, 19, 27, 112, DateTimeKind.Unspecified).AddTicks(8111),
                            DateShipped = new DateTime(2021, 6, 3, 12, 17, 13, 789, DateTimeKind.Unspecified).AddTicks(7864)
                        },
                        new
                        {
                            Id = 24,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 12, 4, 12, 37, 447, DateTimeKind.Unspecified).AddTicks(2230),
                            DateShipped = new DateTime(2021, 5, 23, 19, 37, 37, 570, DateTimeKind.Unspecified).AddTicks(9165)
                        },
                        new
                        {
                            Id = 25,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 15, 1, 25, 44, 556, DateTimeKind.Unspecified).AddTicks(6887),
                            DateShipped = new DateTime(2021, 7, 16, 23, 30, 9, 886, DateTimeKind.Unspecified).AddTicks(7959)
                        },
                        new
                        {
                            Id = 26,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 7, 20, 29, 49, 380, DateTimeKind.Unspecified).AddTicks(6458),
                            DateShipped = new DateTime(2021, 8, 11, 3, 7, 7, 441, DateTimeKind.Unspecified).AddTicks(181)
                        },
                        new
                        {
                            Id = 27,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 5, 39, 55, 638, DateTimeKind.Unspecified).AddTicks(8896),
                            DateShipped = new DateTime(2021, 5, 15, 22, 27, 58, 865, DateTimeKind.Unspecified).AddTicks(1485)
                        },
                        new
                        {
                            Id = 28,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 25, 14, 57, 8, 254, DateTimeKind.Unspecified).AddTicks(7888),
                            DateShipped = new DateTime(2021, 6, 4, 22, 17, 57, 972, DateTimeKind.Unspecified).AddTicks(6119)
                        },
                        new
                        {
                            Id = 29,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 18, 3, 40, 5, 652, DateTimeKind.Unspecified).AddTicks(8600),
                            DateShipped = new DateTime(2021, 7, 16, 3, 54, 45, 458, DateTimeKind.Unspecified).AddTicks(5892)
                        },
                        new
                        {
                            Id = 30,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 11, 4, 45, 51, 872, DateTimeKind.Unspecified).AddTicks(7770),
                            DateShipped = new DateTime(2021, 6, 7, 7, 24, 16, 553, DateTimeKind.Unspecified).AddTicks(2734)
                        },
                        new
                        {
                            Id = 31,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 3, 19, 30, 804, DateTimeKind.Unspecified).AddTicks(9606),
                            DateShipped = new DateTime(2021, 8, 18, 17, 27, 38, 223, DateTimeKind.Unspecified).AddTicks(9995)
                        },
                        new
                        {
                            Id = 32,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 7, 45, 53, 481, DateTimeKind.Unspecified).AddTicks(9465),
                            DateShipped = new DateTime(2021, 7, 1, 14, 42, 5, 125, DateTimeKind.Unspecified).AddTicks(6295)
                        },
                        new
                        {
                            Id = 33,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 18, 3, 0, 0, 324, DateTimeKind.Unspecified).AddTicks(8071),
                            DateShipped = new DateTime(2021, 8, 10, 10, 54, 54, 293, DateTimeKind.Unspecified).AddTicks(1001)
                        },
                        new
                        {
                            Id = 34,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 30, 14, 16, 23, 856, DateTimeKind.Unspecified).AddTicks(3786),
                            DateShipped = new DateTime(2021, 7, 6, 18, 26, 14, 143, DateTimeKind.Unspecified).AddTicks(2126)
                        },
                        new
                        {
                            Id = 35,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 23, 55, 58, 862, DateTimeKind.Unspecified).AddTicks(1004),
                            DateShipped = new DateTime(2021, 7, 19, 13, 40, 3, 276, DateTimeKind.Unspecified).AddTicks(7346)
                        },
                        new
                        {
                            Id = 36,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 17, 7, 20, 19, 267, DateTimeKind.Unspecified).AddTicks(528),
                            DateShipped = new DateTime(2021, 5, 19, 23, 8, 36, 373, DateTimeKind.Unspecified).AddTicks(6344)
                        },
                        new
                        {
                            Id = 37,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 1, 28, 49, 293, DateTimeKind.Unspecified).AddTicks(1641),
                            DateShipped = new DateTime(2021, 7, 13, 2, 11, 19, 515, DateTimeKind.Unspecified).AddTicks(4221)
                        },
                        new
                        {
                            Id = 38,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 24, 4, 59, 55, 307, DateTimeKind.Unspecified).AddTicks(7519),
                            DateShipped = new DateTime(2021, 7, 10, 11, 32, 9, 385, DateTimeKind.Unspecified).AddTicks(6650)
                        },
                        new
                        {
                            Id = 39,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 13, 8, 18, 8, 382, DateTimeKind.Unspecified).AddTicks(2953),
                            DateShipped = new DateTime(2021, 6, 23, 21, 10, 28, 28, DateTimeKind.Unspecified).AddTicks(513)
                        },
                        new
                        {
                            Id = 40,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 15, 18, 52, 16, 273, DateTimeKind.Unspecified).AddTicks(7063),
                            DateShipped = new DateTime(2021, 6, 19, 15, 50, 33, 974, DateTimeKind.Unspecified).AddTicks(5579)
                        },
                        new
                        {
                            Id = 41,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 25, 12, 29, 47, 626, DateTimeKind.Unspecified).AddTicks(1727),
                            DateShipped = new DateTime(2021, 7, 20, 22, 40, 4, 748, DateTimeKind.Unspecified).AddTicks(4778)
                        },
                        new
                        {
                            Id = 42,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 1, 17, 0, 10, 260, DateTimeKind.Unspecified).AddTicks(547),
                            DateShipped = new DateTime(2021, 7, 1, 20, 39, 12, 829, DateTimeKind.Unspecified).AddTicks(1691)
                        },
                        new
                        {
                            Id = 43,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 19, 5, 1, 58, 675, DateTimeKind.Unspecified).AddTicks(7008),
                            DateShipped = new DateTime(2021, 5, 17, 23, 18, 45, 422, DateTimeKind.Unspecified).AddTicks(3931)
                        },
                        new
                        {
                            Id = 44,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 21, 38, 12, 746, DateTimeKind.Unspecified).AddTicks(8037),
                            DateShipped = new DateTime(2021, 5, 27, 22, 9, 19, 315, DateTimeKind.Unspecified).AddTicks(2358)
                        },
                        new
                        {
                            Id = 45,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 16, 42, 14, 161, DateTimeKind.Unspecified).AddTicks(6464),
                            DateShipped = new DateTime(2021, 7, 15, 17, 58, 16, 505, DateTimeKind.Unspecified).AddTicks(2384)
                        },
                        new
                        {
                            Id = 46,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 23, 22, 38, 26, 155, DateTimeKind.Unspecified).AddTicks(6913),
                            DateShipped = new DateTime(2021, 8, 14, 5, 21, 32, 154, DateTimeKind.Unspecified).AddTicks(4299)
                        },
                        new
                        {
                            Id = 47,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 24, 11, 14, 21, 95, DateTimeKind.Unspecified).AddTicks(9852),
                            DateShipped = new DateTime(2021, 7, 15, 9, 12, 10, 330, DateTimeKind.Unspecified).AddTicks(8358)
                        },
                        new
                        {
                            Id = 48,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 16, 57, 25, 184, DateTimeKind.Unspecified).AddTicks(1445),
                            DateShipped = new DateTime(2021, 8, 23, 3, 58, 44, 553, DateTimeKind.Unspecified).AddTicks(4099)
                        },
                        new
                        {
                            Id = 49,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 5, 1, 22, 573, DateTimeKind.Unspecified).AddTicks(6234),
                            DateShipped = new DateTime(2021, 7, 4, 6, 38, 17, 453, DateTimeKind.Unspecified).AddTicks(93)
                        },
                        new
                        {
                            Id = 50,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 12, 59, 49, 287, DateTimeKind.Unspecified).AddTicks(8557),
                            DateShipped = new DateTime(2021, 7, 25, 10, 6, 39, 355, DateTimeKind.Unspecified).AddTicks(5522)
                        },
                        new
                        {
                            Id = 51,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 19, 10, 11, 328, DateTimeKind.Unspecified).AddTicks(1050),
                            DateShipped = new DateTime(2021, 6, 3, 17, 27, 12, 69, DateTimeKind.Unspecified).AddTicks(1222)
                        },
                        new
                        {
                            Id = 52,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 6, 44, 46, 30, DateTimeKind.Unspecified).AddTicks(5840),
                            DateShipped = new DateTime(2021, 8, 7, 20, 43, 35, 584, DateTimeKind.Unspecified).AddTicks(7748)
                        },
                        new
                        {
                            Id = 53,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 1, 20, 57, 766, DateTimeKind.Unspecified).AddTicks(3310),
                            DateShipped = new DateTime(2021, 7, 1, 16, 47, 48, 598, DateTimeKind.Unspecified).AddTicks(8991)
                        },
                        new
                        {
                            Id = 54,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 15, 7, 58, 8, 746, DateTimeKind.Unspecified).AddTicks(4359),
                            DateShipped = new DateTime(2021, 5, 13, 1, 19, 49, 691, DateTimeKind.Unspecified).AddTicks(7857)
                        },
                        new
                        {
                            Id = 55,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 14, 50, 25, 605, DateTimeKind.Unspecified).AddTicks(3533),
                            DateShipped = new DateTime(2021, 6, 20, 10, 48, 51, 259, DateTimeKind.Unspecified).AddTicks(7441)
                        },
                        new
                        {
                            Id = 56,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 2, 9, 35, 5, 52, DateTimeKind.Unspecified).AddTicks(462),
                            DateShipped = new DateTime(2021, 5, 30, 19, 55, 12, 21, DateTimeKind.Unspecified).AddTicks(4841)
                        },
                        new
                        {
                            Id = 57,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 16, 23, 34, 36, 953, DateTimeKind.Unspecified).AddTicks(2614),
                            DateShipped = new DateTime(2021, 6, 20, 15, 29, 21, 616, DateTimeKind.Unspecified).AddTicks(2604)
                        },
                        new
                        {
                            Id = 58,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 28, 17, 23, 0, 515, DateTimeKind.Unspecified).AddTicks(6284),
                            DateShipped = new DateTime(2021, 8, 3, 7, 38, 42, 923, DateTimeKind.Unspecified).AddTicks(1873)
                        },
                        new
                        {
                            Id = 59,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 1, 15, 16, 0, 672, DateTimeKind.Unspecified).AddTicks(2641),
                            DateShipped = new DateTime(2021, 5, 20, 11, 52, 27, 782, DateTimeKind.Unspecified).AddTicks(2756)
                        },
                        new
                        {
                            Id = 60,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 5, 16, 58, 144, DateTimeKind.Unspecified).AddTicks(5300),
                            DateShipped = new DateTime(2021, 5, 11, 17, 58, 44, 529, DateTimeKind.Unspecified).AddTicks(253)
                        },
                        new
                        {
                            Id = 61,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 8, 6, 15, 12, 172, DateTimeKind.Unspecified).AddTicks(1298),
                            DateShipped = new DateTime(2021, 7, 15, 10, 17, 32, 663, DateTimeKind.Unspecified).AddTicks(2139)
                        },
                        new
                        {
                            Id = 62,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 8, 2, 20, 7, 41, DateTimeKind.Unspecified).AddTicks(7905),
                            DateShipped = new DateTime(2021, 7, 4, 2, 35, 30, 541, DateTimeKind.Unspecified).AddTicks(4690)
                        },
                        new
                        {
                            Id = 63,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 25, 4, 2, 5, 439, DateTimeKind.Unspecified).AddTicks(2647),
                            DateShipped = new DateTime(2021, 5, 22, 18, 15, 10, 366, DateTimeKind.Unspecified).AddTicks(8891)
                        },
                        new
                        {
                            Id = 64,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 3, 7, 4, 28, 527, DateTimeKind.Unspecified).AddTicks(3289),
                            DateShipped = new DateTime(2021, 6, 25, 16, 35, 11, 907, DateTimeKind.Unspecified).AddTicks(4489)
                        },
                        new
                        {
                            Id = 65,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 5, 7, 31, 825, DateTimeKind.Unspecified).AddTicks(7346),
                            DateShipped = new DateTime(2021, 7, 4, 9, 14, 22, 617, DateTimeKind.Unspecified).AddTicks(2638)
                        },
                        new
                        {
                            Id = 66,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 18, 17, 10, 56, 283, DateTimeKind.Unspecified).AddTicks(5877),
                            DateShipped = new DateTime(2021, 7, 19, 20, 27, 27, 202, DateTimeKind.Unspecified).AddTicks(7004)
                        },
                        new
                        {
                            Id = 67,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 19, 47, 46, 883, DateTimeKind.Unspecified).AddTicks(7253),
                            DateShipped = new DateTime(2021, 8, 28, 21, 32, 8, 394, DateTimeKind.Unspecified).AddTicks(6860)
                        },
                        new
                        {
                            Id = 68,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 3, 6, 19, 944, DateTimeKind.Unspecified).AddTicks(5145),
                            DateShipped = new DateTime(2021, 8, 7, 6, 58, 20, 948, DateTimeKind.Unspecified).AddTicks(712)
                        },
                        new
                        {
                            Id = 69,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 16, 15, 21, 21, 311, DateTimeKind.Unspecified).AddTicks(2010),
                            DateShipped = new DateTime(2021, 5, 8, 2, 17, 12, 76, DateTimeKind.Unspecified).AddTicks(8573)
                        },
                        new
                        {
                            Id = 70,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 17, 15, 15, 636, DateTimeKind.Unspecified).AddTicks(5967),
                            DateShipped = new DateTime(2021, 6, 14, 10, 59, 45, 736, DateTimeKind.Unspecified).AddTicks(2589)
                        },
                        new
                        {
                            Id = 71,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 25, 16, 40, 31, 269, DateTimeKind.Unspecified).AddTicks(7079),
                            DateShipped = new DateTime(2021, 6, 25, 5, 11, 46, 424, DateTimeKind.Unspecified).AddTicks(1526)
                        },
                        new
                        {
                            Id = 72,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 8, 58, 44, 608, DateTimeKind.Unspecified).AddTicks(3902),
                            DateShipped = new DateTime(2021, 6, 29, 15, 4, 38, 822, DateTimeKind.Unspecified).AddTicks(5322)
                        },
                        new
                        {
                            Id = 73,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 14, 13, 20, 57, 319, DateTimeKind.Unspecified).AddTicks(5219),
                            DateShipped = new DateTime(2021, 6, 21, 12, 6, 11, 821, DateTimeKind.Unspecified).AddTicks(9021)
                        },
                        new
                        {
                            Id = 74,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 20, 20, 15, 20, 236, DateTimeKind.Unspecified).AddTicks(3756),
                            DateShipped = new DateTime(2021, 5, 25, 15, 20, 39, 952, DateTimeKind.Unspecified).AddTicks(3024)
                        },
                        new
                        {
                            Id = 75,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 24, 3, 46, 38, 832, DateTimeKind.Unspecified).AddTicks(4214),
                            DateShipped = new DateTime(2021, 7, 13, 6, 2, 9, 322, DateTimeKind.Unspecified).AddTicks(2216)
                        },
                        new
                        {
                            Id = 76,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 13, 36, 40, 842, DateTimeKind.Unspecified).AddTicks(6686),
                            DateShipped = new DateTime(2021, 8, 26, 7, 11, 4, 538, DateTimeKind.Unspecified).AddTicks(2569)
                        },
                        new
                        {
                            Id = 77,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 8, 20, 28, 1, 964, DateTimeKind.Unspecified).AddTicks(8937),
                            DateShipped = new DateTime(2021, 8, 6, 12, 43, 47, 494, DateTimeKind.Unspecified).AddTicks(7618)
                        },
                        new
                        {
                            Id = 78,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 29, 1, 10, 57, 670, DateTimeKind.Unspecified).AddTicks(484),
                            DateShipped = new DateTime(2021, 6, 16, 0, 6, 8, 484, DateTimeKind.Unspecified).AddTicks(3020)
                        },
                        new
                        {
                            Id = 79,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 25, 20, 2, 42, 666, DateTimeKind.Unspecified).AddTicks(3544),
                            DateShipped = new DateTime(2021, 5, 29, 9, 35, 20, 459, DateTimeKind.Unspecified).AddTicks(437)
                        },
                        new
                        {
                            Id = 80,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 20, 18, 38, 292, DateTimeKind.Unspecified).AddTicks(3121),
                            DateShipped = new DateTime(2021, 6, 13, 14, 1, 41, 205, DateTimeKind.Unspecified).AddTicks(2011)
                        },
                        new
                        {
                            Id = 81,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 3, 4, 35, 28, 692, DateTimeKind.Unspecified).AddTicks(7330),
                            DateShipped = new DateTime(2021, 7, 26, 3, 12, 14, 904, DateTimeKind.Unspecified).AddTicks(1262)
                        },
                        new
                        {
                            Id = 82,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 4, 23, 49, 483, DateTimeKind.Unspecified).AddTicks(4494),
                            DateShipped = new DateTime(2021, 7, 29, 15, 31, 50, 928, DateTimeKind.Unspecified).AddTicks(5466)
                        },
                        new
                        {
                            Id = 83,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 23, 20, 13, 864, DateTimeKind.Unspecified).AddTicks(3999),
                            DateShipped = new DateTime(2021, 7, 19, 19, 45, 53, 601, DateTimeKind.Unspecified).AddTicks(6602)
                        },
                        new
                        {
                            Id = 84,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 10, 26, 9, 395, DateTimeKind.Unspecified).AddTicks(8770),
                            DateShipped = new DateTime(2021, 5, 25, 20, 57, 24, 678, DateTimeKind.Unspecified).AddTicks(7694)
                        },
                        new
                        {
                            Id = 85,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 13, 19, 42, 50, 139, DateTimeKind.Unspecified).AddTicks(2072),
                            DateShipped = new DateTime(2021, 7, 19, 1, 20, 36, 568, DateTimeKind.Unspecified).AddTicks(2565)
                        },
                        new
                        {
                            Id = 86,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 24, 23, 18, 10, 245, DateTimeKind.Unspecified).AddTicks(3560),
                            DateShipped = new DateTime(2021, 6, 19, 8, 51, 49, 370, DateTimeKind.Unspecified).AddTicks(7308)
                        },
                        new
                        {
                            Id = 87,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 29, 12, 14, 41, 676, DateTimeKind.Unspecified).AddTicks(3889),
                            DateShipped = new DateTime(2021, 7, 29, 22, 4, 59, 722, DateTimeKind.Unspecified).AddTicks(7592)
                        },
                        new
                        {
                            Id = 88,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 9, 1, 23, 49, 995, DateTimeKind.Unspecified).AddTicks(4512),
                            DateShipped = new DateTime(2021, 6, 25, 9, 4, 15, 110, DateTimeKind.Unspecified).AddTicks(5204)
                        },
                        new
                        {
                            Id = 89,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 16, 11, 59, 36, 402, DateTimeKind.Unspecified).AddTicks(4816),
                            DateShipped = new DateTime(2021, 5, 25, 18, 35, 26, 132, DateTimeKind.Unspecified).AddTicks(9366)
                        },
                        new
                        {
                            Id = 90,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 19, 9, 10, 13, 463, DateTimeKind.Unspecified).AddTicks(3546),
                            DateShipped = new DateTime(2021, 5, 11, 12, 37, 56, 131, DateTimeKind.Unspecified).AddTicks(9119)
                        },
                        new
                        {
                            Id = 91,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 2, 12, 54, 40, 365, DateTimeKind.Unspecified).AddTicks(1296),
                            DateShipped = new DateTime(2021, 7, 6, 19, 5, 9, 623, DateTimeKind.Unspecified).AddTicks(22)
                        },
                        new
                        {
                            Id = 92,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 2, 1, 18, 46, 234, DateTimeKind.Unspecified).AddTicks(1939),
                            DateShipped = new DateTime(2021, 5, 27, 22, 56, 7, 150, DateTimeKind.Unspecified).AddTicks(7415)
                        },
                        new
                        {
                            Id = 93,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 1, 18, 38, 48, 507, DateTimeKind.Unspecified).AddTicks(7795),
                            DateShipped = new DateTime(2021, 8, 13, 0, 4, 24, 214, DateTimeKind.Unspecified).AddTicks(8615)
                        },
                        new
                        {
                            Id = 94,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 18, 22, 25, 12, 105, DateTimeKind.Unspecified).AddTicks(391),
                            DateShipped = new DateTime(2021, 8, 20, 22, 4, 26, 795, DateTimeKind.Unspecified).AddTicks(8004)
                        },
                        new
                        {
                            Id = 95,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 31, 1, 54, 56, 752, DateTimeKind.Unspecified).AddTicks(6170),
                            DateShipped = new DateTime(2021, 5, 10, 6, 15, 27, 150, DateTimeKind.Unspecified).AddTicks(8456)
                        },
                        new
                        {
                            Id = 96,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 13, 5, 7, 13, 338, DateTimeKind.Unspecified).AddTicks(9711),
                            DateShipped = new DateTime(2021, 6, 21, 15, 20, 17, 8, DateTimeKind.Unspecified).AddTicks(9949)
                        },
                        new
                        {
                            Id = 97,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 4, 34, 32, 716, DateTimeKind.Unspecified).AddTicks(8950),
                            DateShipped = new DateTime(2021, 7, 16, 13, 17, 14, 219, DateTimeKind.Unspecified).AddTicks(8267)
                        },
                        new
                        {
                            Id = 98,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 21, 47, 59, 366, DateTimeKind.Unspecified).AddTicks(6758),
                            DateShipped = new DateTime(2021, 5, 14, 2, 46, 1, 157, DateTimeKind.Unspecified).AddTicks(3206)
                        },
                        new
                        {
                            Id = 99,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 5, 9, 9, 58, 130, DateTimeKind.Unspecified).AddTicks(9091),
                            DateShipped = new DateTime(2021, 7, 15, 18, 57, 57, 87, DateTimeKind.Unspecified).AddTicks(5086)
                        },
                        new
                        {
                            Id = 100,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 17, 17, 53, 51, 497, DateTimeKind.Unspecified).AddTicks(5428),
                            DateShipped = new DateTime(2021, 7, 8, 18, 41, 48, 876, DateTimeKind.Unspecified).AddTicks(630)
                        });
                });

            modelBuilder.Entity("ConsignorManifest", b =>
                {
                    b.HasOne("EPManifest.Core.Consignor", null)
                        .WithMany()
                        .HasForeignKey("ConsignorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Manifest", null)
                        .WithMany()
                        .HasForeignKey("ManifestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.HasOne("EPManifest.Core.Manifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.HasOne("EPManifest.Core.Carrier", "Carrier")
                        .WithMany("Manifests")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Consignee", "Consignee")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EPManifest.Core.Address", "ConsigneeAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsigneeAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.OwnsOne("EPManifest.Core.Address", "ConsignorAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsignorAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeAddress");

                    b.Navigation("ConsignorAddress");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
