// <auto-generated />
using System;
using EPManifest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPManifest.Data.Migrations
{
    [DbContext(typeof(EPManifestDbContext))]
    [Migration("20210526063650_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsignorManifest", b =>
                {
                    b.Property<int>("ConsignorsId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestsId")
                        .HasColumnType("int");

                    b.HasKey("ConsignorsId", "ManifestsId");

                    b.HasIndex("ManifestsId");

                    b.ToTable("ConsignorManifest");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "50101",
                            Name = "A1 Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Code = "10-4010",
                            Name = "Pacific Northwest Freight"
                        },
                        new
                        {
                            Id = 3,
                            Code = "40-020",
                            Name = "AP Freight"
                        },
                        new
                        {
                            Id = 4,
                            Code = "60-10",
                            Name = "NM Shipping Inc"
                        },
                        new
                        {
                            Id = 5,
                            Code = "60-05",
                            Name = "Frank's Freight"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AB-120",
                            Name = "Pete's Disposal"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AB-410",
                            Name = "ATI Environmental"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AB-019",
                            Name = "EQ Enviro"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AB-918",
                            Name = "Whitehorse Landfill"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AB-412",
                            Name = "YAE"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OXP-4",
                            Name = "Carmacks Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Code = "A-000",
                            Name = "Mayo Health Centre"
                        },
                        new
                        {
                            Id = 3,
                            Code = "B-5010",
                            Name = "Whitehorse General Hospital"
                        },
                        new
                        {
                            Id = 4,
                            Code = "A1-102",
                            Name = "Teslin Health Centre"
                        },
                        new
                        {
                            Id = 5,
                            Code = "A840",
                            Name = "Whistle Bend Place"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShipped")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ConsigneeId");

                    b.ToTable("Manifests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 2,
                            Code = "YT30178-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 9, 16, 57, 28, 441, DateTimeKind.Unspecified).AddTicks(6605),
                            DateShipped = new DateTime(2021, 5, 27, 19, 53, 20, 540, DateTimeKind.Unspecified).AddTicks(9380)
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 4,
                            Code = "YT65625-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 2, 0, 32, 31, 953, DateTimeKind.Unspecified).AddTicks(6460),
                            DateShipped = new DateTime(2021, 8, 4, 0, 1, 17, 678, DateTimeKind.Unspecified).AddTicks(4763)
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 5,
                            Code = "YT18884-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 22, 51, 36, 505, DateTimeKind.Unspecified).AddTicks(559),
                            DateShipped = new DateTime(2021, 5, 31, 20, 25, 19, 495, DateTimeKind.Unspecified).AddTicks(44)
                        },
                        new
                        {
                            Id = 4,
                            CarrierId = 3,
                            Code = "YT20188-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 21, 4, 39, 50, 864, DateTimeKind.Unspecified).AddTicks(4352),
                            DateShipped = new DateTime(2021, 6, 11, 20, 13, 51, 149, DateTimeKind.Unspecified).AddTicks(2305)
                        },
                        new
                        {
                            Id = 5,
                            CarrierId = 3,
                            Code = "YT82508-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 17, 15, 22, 2, 127, DateTimeKind.Unspecified).AddTicks(5557),
                            DateShipped = new DateTime(2021, 7, 9, 2, 8, 52, 259, DateTimeKind.Unspecified).AddTicks(6526)
                        },
                        new
                        {
                            Id = 6,
                            CarrierId = 5,
                            Code = "YT13605-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 22, 3, 52, 234, DateTimeKind.Unspecified).AddTicks(4107),
                            DateShipped = new DateTime(2021, 6, 1, 10, 38, 10, 955, DateTimeKind.Unspecified).AddTicks(5524)
                        },
                        new
                        {
                            Id = 7,
                            CarrierId = 2,
                            Code = "YT94562-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 6, 19, 33, 23, 627, DateTimeKind.Unspecified).AddTicks(3733),
                            DateShipped = new DateTime(2021, 6, 19, 21, 46, 48, 67, DateTimeKind.Unspecified).AddTicks(2436)
                        },
                        new
                        {
                            Id = 8,
                            CarrierId = 1,
                            Code = "YT71976-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 9, 12, 49, 0, 591, DateTimeKind.Unspecified).AddTicks(9573),
                            DateShipped = new DateTime(2021, 8, 30, 8, 35, 20, 122, DateTimeKind.Unspecified).AddTicks(8673)
                        },
                        new
                        {
                            Id = 9,
                            CarrierId = 4,
                            Code = "YT21532-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 19, 22, 14, 47, 938, DateTimeKind.Unspecified).AddTicks(2775),
                            DateShipped = new DateTime(2021, 7, 8, 17, 25, 39, 660, DateTimeKind.Unspecified).AddTicks(479)
                        },
                        new
                        {
                            Id = 10,
                            CarrierId = 5,
                            Code = "YT99284-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 9, 13, 22, 55, 644, DateTimeKind.Unspecified).AddTicks(9715),
                            DateShipped = new DateTime(2021, 7, 6, 18, 24, 30, 349, DateTimeKind.Unspecified).AddTicks(9715)
                        },
                        new
                        {
                            Id = 11,
                            CarrierId = 4,
                            Code = "YT97863-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 22, 5, 56, 57, 499, DateTimeKind.Unspecified).AddTicks(6118),
                            DateShipped = new DateTime(2021, 7, 18, 9, 8, 52, 735, DateTimeKind.Unspecified).AddTicks(8101)
                        },
                        new
                        {
                            Id = 12,
                            CarrierId = 3,
                            Code = "YT36044-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 13, 47, 10, 902, DateTimeKind.Unspecified).AddTicks(9810),
                            DateShipped = new DateTime(2021, 8, 21, 15, 35, 13, 682, DateTimeKind.Unspecified).AddTicks(7879)
                        },
                        new
                        {
                            Id = 13,
                            CarrierId = 4,
                            Code = "YT15300-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 30, 20, 19, 26, 659, DateTimeKind.Unspecified).AddTicks(1791),
                            DateShipped = new DateTime(2021, 8, 19, 5, 26, 42, 755, DateTimeKind.Unspecified).AddTicks(8433)
                        },
                        new
                        {
                            Id = 14,
                            CarrierId = 4,
                            Code = "YT24331-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 15, 4, 6, 53, 603, DateTimeKind.Unspecified).AddTicks(9460),
                            DateShipped = new DateTime(2021, 6, 16, 0, 25, 12, 148, DateTimeKind.Unspecified).AddTicks(5881)
                        },
                        new
                        {
                            Id = 15,
                            CarrierId = 3,
                            Code = "YT32493-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 9, 12, 38, 5, 297, DateTimeKind.Unspecified).AddTicks(5431),
                            DateShipped = new DateTime(2021, 8, 11, 17, 7, 37, 288, DateTimeKind.Unspecified).AddTicks(6098)
                        },
                        new
                        {
                            Id = 16,
                            CarrierId = 4,
                            Code = "YT96661-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 22, 2, 29, 621, DateTimeKind.Unspecified).AddTicks(3403),
                            DateShipped = new DateTime(2021, 6, 6, 14, 14, 59, 47, DateTimeKind.Unspecified).AddTicks(3435)
                        },
                        new
                        {
                            Id = 17,
                            CarrierId = 3,
                            Code = "YT70586-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 2, 59, 39, 885, DateTimeKind.Unspecified).AddTicks(3686),
                            DateShipped = new DateTime(2021, 8, 11, 1, 3, 52, 192, DateTimeKind.Unspecified).AddTicks(2514)
                        },
                        new
                        {
                            Id = 18,
                            CarrierId = 3,
                            Code = "YT86755-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 12, 20, 6, 271, DateTimeKind.Unspecified).AddTicks(8121),
                            DateShipped = new DateTime(2021, 7, 15, 19, 21, 47, 720, DateTimeKind.Unspecified).AddTicks(4656)
                        },
                        new
                        {
                            Id = 19,
                            CarrierId = 3,
                            Code = "YT24756-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 10, 4, 37, 401, DateTimeKind.Unspecified).AddTicks(7980),
                            DateShipped = new DateTime(2021, 8, 6, 5, 14, 11, 713, DateTimeKind.Unspecified).AddTicks(2862)
                        },
                        new
                        {
                            Id = 20,
                            CarrierId = 3,
                            Code = "YT52081-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 29, 18, 44, 25, 998, DateTimeKind.Unspecified).AddTicks(6870),
                            DateShipped = new DateTime(2021, 6, 20, 17, 40, 14, 910, DateTimeKind.Unspecified).AddTicks(183)
                        },
                        new
                        {
                            Id = 21,
                            CarrierId = 4,
                            Code = "YT65673-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 21, 15, 57, 7, 268, DateTimeKind.Unspecified).AddTicks(7837),
                            DateShipped = new DateTime(2021, 6, 27, 16, 14, 54, 201, DateTimeKind.Unspecified).AddTicks(7619)
                        },
                        new
                        {
                            Id = 22,
                            CarrierId = 4,
                            Code = "YT56070-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 13, 8, 58, 880, DateTimeKind.Unspecified).AddTicks(2481),
                            DateShipped = new DateTime(2021, 5, 15, 22, 59, 48, 673, DateTimeKind.Unspecified).AddTicks(7404)
                        },
                        new
                        {
                            Id = 23,
                            CarrierId = 4,
                            Code = "YT83739-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 14, 9, 8, 5, 852, DateTimeKind.Unspecified).AddTicks(3790),
                            DateShipped = new DateTime(2021, 8, 22, 7, 18, 33, 544, DateTimeKind.Unspecified).AddTicks(1903)
                        },
                        new
                        {
                            Id = 24,
                            CarrierId = 1,
                            Code = "YT19800-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 10, 11, 56, 9, 714, DateTimeKind.Unspecified).AddTicks(9283),
                            DateShipped = new DateTime(2021, 6, 22, 20, 21, 51, 142, DateTimeKind.Unspecified).AddTicks(5235)
                        },
                        new
                        {
                            Id = 25,
                            CarrierId = 2,
                            Code = "YT85084-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 1, 19, 11, 921, DateTimeKind.Unspecified).AddTicks(7230),
                            DateShipped = new DateTime(2021, 6, 6, 4, 5, 56, 136, DateTimeKind.Unspecified).AddTicks(7059)
                        },
                        new
                        {
                            Id = 26,
                            CarrierId = 4,
                            Code = "YT46999-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 13, 1, 38, 22, 544, DateTimeKind.Unspecified).AddTicks(482),
                            DateShipped = new DateTime(2021, 8, 27, 0, 51, 29, 142, DateTimeKind.Unspecified).AddTicks(6905)
                        },
                        new
                        {
                            Id = 27,
                            CarrierId = 2,
                            Code = "YT35015-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 2, 12, 57, 25, 703, DateTimeKind.Unspecified).AddTicks(1586),
                            DateShipped = new DateTime(2021, 5, 10, 17, 49, 26, 757, DateTimeKind.Unspecified).AddTicks(353)
                        },
                        new
                        {
                            Id = 28,
                            CarrierId = 5,
                            Code = "YT13138-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 26, 8, 5, 14, 280, DateTimeKind.Unspecified).AddTicks(3983),
                            DateShipped = new DateTime(2021, 8, 5, 17, 47, 7, 872, DateTimeKind.Unspecified).AddTicks(2927)
                        },
                        new
                        {
                            Id = 29,
                            CarrierId = 1,
                            Code = "YT96993-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 20, 14, 26, 12, 93, DateTimeKind.Unspecified).AddTicks(5825),
                            DateShipped = new DateTime(2021, 6, 23, 13, 59, 22, 98, DateTimeKind.Unspecified).AddTicks(1302)
                        },
                        new
                        {
                            Id = 30,
                            CarrierId = 5,
                            Code = "YT50799-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 10, 8, 54, 47, 387, DateTimeKind.Unspecified).AddTicks(2266),
                            DateShipped = new DateTime(2021, 8, 9, 0, 19, 37, 743, DateTimeKind.Unspecified).AddTicks(3207)
                        },
                        new
                        {
                            Id = 31,
                            CarrierId = 3,
                            Code = "YT74036-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 2, 35, 11, 15, DateTimeKind.Unspecified).AddTicks(5641),
                            DateShipped = new DateTime(2021, 6, 18, 6, 31, 7, 920, DateTimeKind.Unspecified).AddTicks(7181)
                        },
                        new
                        {
                            Id = 32,
                            CarrierId = 4,
                            Code = "YT24505-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 26, 11, 17, 25, 968, DateTimeKind.Unspecified).AddTicks(8108),
                            DateShipped = new DateTime(2021, 6, 18, 1, 56, 7, 552, DateTimeKind.Unspecified).AddTicks(9572)
                        },
                        new
                        {
                            Id = 33,
                            CarrierId = 3,
                            Code = "YT39773-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 1, 13, 40, 12, 105, DateTimeKind.Unspecified).AddTicks(3329),
                            DateShipped = new DateTime(2021, 5, 20, 23, 41, 27, 918, DateTimeKind.Unspecified).AddTicks(4837)
                        },
                        new
                        {
                            Id = 34,
                            CarrierId = 1,
                            Code = "YT46193-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 23, 21, 4, 951, DateTimeKind.Unspecified).AddTicks(1475),
                            DateShipped = new DateTime(2021, 6, 10, 12, 14, 0, 546, DateTimeKind.Unspecified).AddTicks(8594)
                        },
                        new
                        {
                            Id = 35,
                            CarrierId = 1,
                            Code = "YT80529-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 30, 20, 42, 0, 244, DateTimeKind.Unspecified).AddTicks(3544),
                            DateShipped = new DateTime(2021, 6, 4, 15, 11, 30, 905, DateTimeKind.Unspecified).AddTicks(1896)
                        },
                        new
                        {
                            Id = 36,
                            CarrierId = 2,
                            Code = "YT79451-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 3, 3, 54, 11, 373, DateTimeKind.Unspecified).AddTicks(6001),
                            DateShipped = new DateTime(2021, 7, 18, 12, 10, 42, 759, DateTimeKind.Unspecified).AddTicks(7205)
                        },
                        new
                        {
                            Id = 37,
                            CarrierId = 2,
                            Code = "YT25899-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 5, 6, 20, 11, DateTimeKind.Unspecified).AddTicks(5596),
                            DateShipped = new DateTime(2021, 8, 1, 2, 10, 30, 401, DateTimeKind.Unspecified).AddTicks(7074)
                        },
                        new
                        {
                            Id = 38,
                            CarrierId = 3,
                            Code = "YT63983-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 16, 4, 3, 17, 219, DateTimeKind.Unspecified).AddTicks(1610),
                            DateShipped = new DateTime(2021, 8, 15, 13, 40, 39, 274, DateTimeKind.Unspecified).AddTicks(3668)
                        },
                        new
                        {
                            Id = 39,
                            CarrierId = 2,
                            Code = "YT97821-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 15, 22, 49, 22, 194, DateTimeKind.Unspecified).AddTicks(7001),
                            DateShipped = new DateTime(2021, 6, 29, 14, 10, 5, 511, DateTimeKind.Unspecified).AddTicks(3777)
                        },
                        new
                        {
                            Id = 40,
                            CarrierId = 4,
                            Code = "YT54512-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 18, 11, 24, 1, 202, DateTimeKind.Unspecified).AddTicks(9174),
                            DateShipped = new DateTime(2021, 8, 5, 17, 38, 22, 692, DateTimeKind.Unspecified).AddTicks(2805)
                        },
                        new
                        {
                            Id = 41,
                            CarrierId = 1,
                            Code = "YT24024-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 23, 14, 4, 18, 279, DateTimeKind.Unspecified).AddTicks(3844),
                            DateShipped = new DateTime(2021, 8, 30, 1, 38, 35, 580, DateTimeKind.Unspecified).AddTicks(1473)
                        },
                        new
                        {
                            Id = 42,
                            CarrierId = 5,
                            Code = "YT38232-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 17, 16, 27, 16, 796, DateTimeKind.Unspecified).AddTicks(8492),
                            DateShipped = new DateTime(2021, 6, 16, 22, 17, 37, 942, DateTimeKind.Unspecified).AddTicks(5858)
                        },
                        new
                        {
                            Id = 43,
                            CarrierId = 5,
                            Code = "YT97265-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 16, 39, 49, 949, DateTimeKind.Unspecified).AddTicks(1515),
                            DateShipped = new DateTime(2021, 6, 23, 5, 51, 52, 452, DateTimeKind.Unspecified).AddTicks(1011)
                        },
                        new
                        {
                            Id = 44,
                            CarrierId = 1,
                            Code = "YT95148-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 14, 37, 51, 546, DateTimeKind.Unspecified).AddTicks(3571),
                            DateShipped = new DateTime(2021, 5, 12, 3, 46, 45, 60, DateTimeKind.Unspecified).AddTicks(6716)
                        },
                        new
                        {
                            Id = 45,
                            CarrierId = 3,
                            Code = "YT22317-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 9, 7, 16, 700, DateTimeKind.Unspecified).AddTicks(6038),
                            DateShipped = new DateTime(2021, 7, 28, 20, 44, 14, 345, DateTimeKind.Unspecified).AddTicks(5784)
                        },
                        new
                        {
                            Id = 46,
                            CarrierId = 5,
                            Code = "YT82667-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 11, 11, 22, 17, 676, DateTimeKind.Unspecified).AddTicks(9450),
                            DateShipped = new DateTime(2021, 5, 21, 4, 27, 7, 276, DateTimeKind.Unspecified).AddTicks(5428)
                        },
                        new
                        {
                            Id = 47,
                            CarrierId = 3,
                            Code = "YT79230-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 17, 10, 55, 884, DateTimeKind.Unspecified).AddTicks(5957),
                            DateShipped = new DateTime(2021, 6, 5, 7, 50, 52, 459, DateTimeKind.Unspecified).AddTicks(818)
                        },
                        new
                        {
                            Id = 48,
                            CarrierId = 4,
                            Code = "YT52815-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 9, 39, 23, 71, DateTimeKind.Unspecified).AddTicks(6083),
                            DateShipped = new DateTime(2021, 6, 17, 16, 17, 30, 478, DateTimeKind.Unspecified).AddTicks(9268)
                        },
                        new
                        {
                            Id = 49,
                            CarrierId = 5,
                            Code = "YT71412-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 7, 8, 31, 23, 635, DateTimeKind.Unspecified).AddTicks(8377),
                            DateShipped = new DateTime(2021, 7, 29, 9, 56, 16, 2, DateTimeKind.Unspecified).AddTicks(1436)
                        },
                        new
                        {
                            Id = 50,
                            CarrierId = 3,
                            Code = "YT81620-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 5, 18, 29, 31, 386, DateTimeKind.Unspecified).AddTicks(2789),
                            DateShipped = new DateTime(2021, 8, 28, 11, 14, 6, 220, DateTimeKind.Unspecified).AddTicks(249)
                        },
                        new
                        {
                            Id = 51,
                            CarrierId = 2,
                            Code = "YT97978-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 19, 51, 36, 150, DateTimeKind.Unspecified).AddTicks(8786),
                            DateShipped = new DateTime(2021, 5, 20, 23, 49, 38, 374, DateTimeKind.Unspecified).AddTicks(2827)
                        },
                        new
                        {
                            Id = 52,
                            CarrierId = 4,
                            Code = "YT95628-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 23, 25, 52, 121, DateTimeKind.Unspecified).AddTicks(3060),
                            DateShipped = new DateTime(2021, 5, 26, 6, 47, 18, 391, DateTimeKind.Unspecified).AddTicks(4555)
                        },
                        new
                        {
                            Id = 53,
                            CarrierId = 4,
                            Code = "YT88954-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 28, 16, 7, 39, 0, DateTimeKind.Unspecified).AddTicks(9840),
                            DateShipped = new DateTime(2021, 7, 21, 15, 2, 48, 993, DateTimeKind.Unspecified).AddTicks(3552)
                        },
                        new
                        {
                            Id = 54,
                            CarrierId = 4,
                            Code = "YT75571-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 18, 14, 29, 45, 892, DateTimeKind.Unspecified).AddTicks(3827),
                            DateShipped = new DateTime(2021, 8, 12, 22, 33, 11, 873, DateTimeKind.Unspecified).AddTicks(1874)
                        },
                        new
                        {
                            Id = 55,
                            CarrierId = 1,
                            Code = "YT64430-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 2, 26, 1, 314, DateTimeKind.Unspecified).AddTicks(6629),
                            DateShipped = new DateTime(2021, 5, 18, 21, 53, 0, 900, DateTimeKind.Unspecified).AddTicks(2245)
                        },
                        new
                        {
                            Id = 56,
                            CarrierId = 4,
                            Code = "YT52985-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 26, 9, 52, 23, 475, DateTimeKind.Unspecified).AddTicks(9052),
                            DateShipped = new DateTime(2021, 7, 11, 6, 33, 27, 23, DateTimeKind.Unspecified).AddTicks(9266)
                        },
                        new
                        {
                            Id = 57,
                            CarrierId = 4,
                            Code = "YT39604-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 4, 5, 58, 16, 112, DateTimeKind.Unspecified).AddTicks(6234),
                            DateShipped = new DateTime(2021, 8, 3, 21, 45, 9, 400, DateTimeKind.Unspecified).AddTicks(7097)
                        },
                        new
                        {
                            Id = 58,
                            CarrierId = 2,
                            Code = "YT37776-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 3, 30, 33, 245, DateTimeKind.Unspecified).AddTicks(6648),
                            DateShipped = new DateTime(2021, 8, 30, 15, 20, 19, 437, DateTimeKind.Unspecified).AddTicks(8693)
                        },
                        new
                        {
                            Id = 59,
                            CarrierId = 1,
                            Code = "YT62139-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 7, 9, 23, 30, 199, DateTimeKind.Unspecified).AddTicks(4881),
                            DateShipped = new DateTime(2021, 8, 13, 7, 2, 18, 650, DateTimeKind.Unspecified).AddTicks(1818)
                        },
                        new
                        {
                            Id = 60,
                            CarrierId = 2,
                            Code = "YT50405-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 17, 51, 10, 940, DateTimeKind.Unspecified).AddTicks(551),
                            DateShipped = new DateTime(2021, 7, 20, 5, 26, 15, 745, DateTimeKind.Unspecified).AddTicks(9314)
                        },
                        new
                        {
                            Id = 61,
                            CarrierId = 5,
                            Code = "YT13240-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 26, 16, 27, 41, 387, DateTimeKind.Unspecified).AddTicks(7036),
                            DateShipped = new DateTime(2021, 5, 22, 8, 52, 48, 129, DateTimeKind.Unspecified).AddTicks(4545)
                        },
                        new
                        {
                            Id = 62,
                            CarrierId = 3,
                            Code = "YT46916-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 4, 24, 33, 625, DateTimeKind.Unspecified).AddTicks(3142),
                            DateShipped = new DateTime(2021, 6, 8, 23, 56, 22, 17, DateTimeKind.Unspecified).AddTicks(1147)
                        },
                        new
                        {
                            Id = 63,
                            CarrierId = 5,
                            Code = "YT13451-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 2, 8, 14, 40, 724, DateTimeKind.Unspecified).AddTicks(3992),
                            DateShipped = new DateTime(2021, 6, 14, 14, 17, 44, 558, DateTimeKind.Unspecified).AddTicks(7773)
                        },
                        new
                        {
                            Id = 64,
                            CarrierId = 3,
                            Code = "YT76428-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 19, 15, 50, 50, 257, DateTimeKind.Unspecified).AddTicks(4709),
                            DateShipped = new DateTime(2021, 7, 10, 18, 44, 44, 335, DateTimeKind.Unspecified).AddTicks(4212)
                        },
                        new
                        {
                            Id = 65,
                            CarrierId = 5,
                            Code = "YT73111-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 5, 52, 38, 298, DateTimeKind.Unspecified).AddTicks(5634),
                            DateShipped = new DateTime(2021, 6, 2, 3, 20, 44, 841, DateTimeKind.Unspecified).AddTicks(3324)
                        },
                        new
                        {
                            Id = 66,
                            CarrierId = 4,
                            Code = "YT56127-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 24, 13, 50, 20, 427, DateTimeKind.Unspecified).AddTicks(7628),
                            DateShipped = new DateTime(2021, 7, 28, 23, 46, 50, 771, DateTimeKind.Unspecified).AddTicks(7719)
                        },
                        new
                        {
                            Id = 67,
                            CarrierId = 3,
                            Code = "YT36165-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 5, 5, 50, 11, 756, DateTimeKind.Unspecified).AddTicks(9321),
                            DateShipped = new DateTime(2021, 8, 28, 17, 6, 10, 899, DateTimeKind.Unspecified).AddTicks(8609)
                        },
                        new
                        {
                            Id = 68,
                            CarrierId = 5,
                            Code = "YT51061-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 14, 20, 6, 59, 241, DateTimeKind.Unspecified).AddTicks(5470),
                            DateShipped = new DateTime(2021, 5, 18, 19, 20, 30, 637, DateTimeKind.Unspecified).AddTicks(4397)
                        },
                        new
                        {
                            Id = 69,
                            CarrierId = 1,
                            Code = "YT91029-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 22, 2, 13, 49, 948, DateTimeKind.Unspecified).AddTicks(2010),
                            DateShipped = new DateTime(2021, 7, 7, 19, 50, 19, 398, DateTimeKind.Unspecified).AddTicks(6093)
                        },
                        new
                        {
                            Id = 70,
                            CarrierId = 1,
                            Code = "YT31895-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 4, 8, 6, 29, 500, DateTimeKind.Unspecified).AddTicks(3082),
                            DateShipped = new DateTime(2021, 6, 3, 17, 7, 13, 156, DateTimeKind.Unspecified).AddTicks(914)
                        },
                        new
                        {
                            Id = 71,
                            CarrierId = 4,
                            Code = "YT65416-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 4, 11, 7, 121, DateTimeKind.Unspecified).AddTicks(9836),
                            DateShipped = new DateTime(2021, 5, 8, 18, 56, 2, 742, DateTimeKind.Unspecified).AddTicks(1622)
                        },
                        new
                        {
                            Id = 72,
                            CarrierId = 4,
                            Code = "YT83557-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 25, 4, 5, 5, 509, DateTimeKind.Unspecified).AddTicks(1390),
                            DateShipped = new DateTime(2021, 7, 7, 20, 19, 58, 578, DateTimeKind.Unspecified).AddTicks(4588)
                        },
                        new
                        {
                            Id = 73,
                            CarrierId = 1,
                            Code = "YT82750-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 30, 20, 32, 17, 451, DateTimeKind.Unspecified).AddTicks(5386),
                            DateShipped = new DateTime(2021, 5, 11, 21, 57, 46, 397, DateTimeKind.Unspecified).AddTicks(1271)
                        },
                        new
                        {
                            Id = 74,
                            CarrierId = 3,
                            Code = "YT99632-1",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 11, 7, 52, 24, 339, DateTimeKind.Unspecified).AddTicks(8146),
                            DateShipped = new DateTime(2021, 5, 13, 17, 10, 49, 226, DateTimeKind.Unspecified).AddTicks(8165)
                        },
                        new
                        {
                            Id = 75,
                            CarrierId = 1,
                            Code = "YT28163-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 21, 5, 40, 22, 66, DateTimeKind.Unspecified).AddTicks(6682),
                            DateShipped = new DateTime(2021, 7, 6, 17, 36, 51, 577, DateTimeKind.Unspecified).AddTicks(9084)
                        },
                        new
                        {
                            Id = 76,
                            CarrierId = 1,
                            Code = "YT71563-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 2, 21, 57, 55, 236, DateTimeKind.Unspecified).AddTicks(9906),
                            DateShipped = new DateTime(2021, 8, 11, 3, 21, 57, 708, DateTimeKind.Unspecified).AddTicks(7706)
                        },
                        new
                        {
                            Id = 77,
                            CarrierId = 4,
                            Code = "YT81640-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 9, 0, 24, 50, 885, DateTimeKind.Unspecified).AddTicks(1347),
                            DateShipped = new DateTime(2021, 5, 25, 6, 32, 32, 754, DateTimeKind.Unspecified).AddTicks(4161)
                        },
                        new
                        {
                            Id = 78,
                            CarrierId = 1,
                            Code = "YT63981-0",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 29, 7, 10, 54, 49, DateTimeKind.Unspecified).AddTicks(3177),
                            DateShipped = new DateTime(2021, 6, 19, 23, 59, 38, 960, DateTimeKind.Unspecified).AddTicks(6452)
                        },
                        new
                        {
                            Id = 79,
                            CarrierId = 4,
                            Code = "YT26908-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 31, 7, 47, 56, 486, DateTimeKind.Unspecified).AddTicks(5097),
                            DateShipped = new DateTime(2021, 5, 17, 9, 55, 21, 422, DateTimeKind.Unspecified).AddTicks(3149)
                        },
                        new
                        {
                            Id = 80,
                            CarrierId = 3,
                            Code = "YT57547-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 21, 20, 49, 0, 618, DateTimeKind.Unspecified).AddTicks(2161),
                            DateShipped = new DateTime(2021, 6, 26, 16, 24, 31, 474, DateTimeKind.Unspecified).AddTicks(3100)
                        },
                        new
                        {
                            Id = 81,
                            CarrierId = 1,
                            Code = "YT71499-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 9, 6, 7, 36, 761, DateTimeKind.Unspecified).AddTicks(5239),
                            DateShipped = new DateTime(2021, 5, 10, 22, 50, 55, 929, DateTimeKind.Unspecified).AddTicks(8988)
                        },
                        new
                        {
                            Id = 82,
                            CarrierId = 4,
                            Code = "YT82810-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 26, 14, 39, 6, 545, DateTimeKind.Unspecified).AddTicks(1456),
                            DateShipped = new DateTime(2021, 6, 17, 15, 2, 15, 68, DateTimeKind.Unspecified).AddTicks(916)
                        },
                        new
                        {
                            Id = 83,
                            CarrierId = 3,
                            Code = "YT49743-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 13, 22, 47, 58, 249, DateTimeKind.Unspecified).AddTicks(5911),
                            DateShipped = new DateTime(2021, 8, 17, 11, 21, 39, 537, DateTimeKind.Unspecified).AddTicks(7031)
                        },
                        new
                        {
                            Id = 84,
                            CarrierId = 2,
                            Code = "YT54053-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 22, 11, 26, 7, 279, DateTimeKind.Unspecified).AddTicks(7633),
                            DateShipped = new DateTime(2021, 8, 29, 12, 58, 48, 679, DateTimeKind.Unspecified).AddTicks(9365)
                        },
                        new
                        {
                            Id = 85,
                            CarrierId = 4,
                            Code = "YT69000-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 23, 22, 37, 39, 31, DateTimeKind.Unspecified).AddTicks(4246),
                            DateShipped = new DateTime(2021, 7, 21, 9, 20, 53, 294, DateTimeKind.Unspecified).AddTicks(3242)
                        },
                        new
                        {
                            Id = 86,
                            CarrierId = 2,
                            Code = "YT19856-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 1, 11, 26, 15, 690, DateTimeKind.Unspecified).AddTicks(2991),
                            DateShipped = new DateTime(2021, 5, 9, 5, 35, 43, 842, DateTimeKind.Unspecified).AddTicks(9911)
                        },
                        new
                        {
                            Id = 87,
                            CarrierId = 4,
                            Code = "YT15589-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 15, 7, 30, 67, DateTimeKind.Unspecified).AddTicks(5500),
                            DateShipped = new DateTime(2021, 6, 6, 5, 43, 30, 190, DateTimeKind.Unspecified).AddTicks(2506)
                        },
                        new
                        {
                            Id = 88,
                            CarrierId = 2,
                            Code = "YT78952-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 4, 9, 3, 54, 469, DateTimeKind.Unspecified).AddTicks(1920),
                            DateShipped = new DateTime(2021, 6, 14, 13, 25, 13, 848, DateTimeKind.Unspecified).AddTicks(8488)
                        },
                        new
                        {
                            Id = 89,
                            CarrierId = 3,
                            Code = "YT92351-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 6, 12, 14, 17, 203, DateTimeKind.Unspecified).AddTicks(4981),
                            DateShipped = new DateTime(2021, 8, 20, 21, 33, 18, 138, DateTimeKind.Unspecified).AddTicks(615)
                        },
                        new
                        {
                            Id = 90,
                            CarrierId = 2,
                            Code = "YT74820-0",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 14, 6, 55, 19, 815, DateTimeKind.Unspecified).AddTicks(7605),
                            DateShipped = new DateTime(2021, 6, 28, 0, 57, 20, 635, DateTimeKind.Unspecified).AddTicks(509)
                        },
                        new
                        {
                            Id = 91,
                            CarrierId = 4,
                            Code = "YT26656-0",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 26, 0, 39, 0, 351, DateTimeKind.Unspecified).AddTicks(1371),
                            DateShipped = new DateTime(2021, 7, 16, 13, 33, 30, 809, DateTimeKind.Unspecified).AddTicks(9837)
                        },
                        new
                        {
                            Id = 92,
                            CarrierId = 1,
                            Code = "YT83917-0",
                            ConsigneeId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 17, 5, 14, 20, 996, DateTimeKind.Unspecified).AddTicks(8407),
                            DateShipped = new DateTime(2021, 6, 19, 15, 42, 3, 924, DateTimeKind.Unspecified).AddTicks(2161)
                        },
                        new
                        {
                            Id = 93,
                            CarrierId = 2,
                            Code = "YT72473-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 2, 4, 16, 43, 118, DateTimeKind.Unspecified).AddTicks(5922),
                            DateShipped = new DateTime(2021, 7, 8, 7, 1, 40, 952, DateTimeKind.Unspecified).AddTicks(6192)
                        },
                        new
                        {
                            Id = 94,
                            CarrierId = 2,
                            Code = "YT71622-0",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 6, 17, 45, 36, 454, DateTimeKind.Unspecified).AddTicks(6433),
                            DateShipped = new DateTime(2021, 7, 30, 20, 42, 30, 470, DateTimeKind.Unspecified).AddTicks(5031)
                        },
                        new
                        {
                            Id = 95,
                            CarrierId = 1,
                            Code = "YT49829-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 15, 19, 24, 19, 8, DateTimeKind.Unspecified).AddTicks(378),
                            DateShipped = new DateTime(2021, 7, 22, 11, 16, 58, 430, DateTimeKind.Unspecified).AddTicks(8793)
                        },
                        new
                        {
                            Id = 96,
                            CarrierId = 1,
                            Code = "YT86793-1",
                            ConsigneeId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 19, 53, 13, 355, DateTimeKind.Unspecified).AddTicks(3806),
                            DateShipped = new DateTime(2021, 7, 15, 20, 38, 10, 511, DateTimeKind.Unspecified).AddTicks(5429)
                        },
                        new
                        {
                            Id = 97,
                            CarrierId = 4,
                            Code = "YT77900-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 2, 15, 23, 49, 646, DateTimeKind.Unspecified).AddTicks(9887),
                            DateShipped = new DateTime(2021, 7, 2, 1, 15, 45, 117, DateTimeKind.Unspecified).AddTicks(7752)
                        },
                        new
                        {
                            Id = 98,
                            CarrierId = 5,
                            Code = "YT53994-1",
                            ConsigneeId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 25, 23, 45, 34, 308, DateTimeKind.Unspecified).AddTicks(7788),
                            DateShipped = new DateTime(2021, 8, 14, 13, 53, 30, 438, DateTimeKind.Unspecified).AddTicks(379)
                        },
                        new
                        {
                            Id = 99,
                            CarrierId = 1,
                            Code = "YT46824-1",
                            ConsigneeId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 16, 21, 39, 41, DateTimeKind.Unspecified).AddTicks(8515),
                            DateShipped = new DateTime(2021, 7, 21, 7, 12, 23, 806, DateTimeKind.Unspecified).AddTicks(4651)
                        },
                        new
                        {
                            Id = 100,
                            CarrierId = 3,
                            Code = "YT56851-1",
                            ConsigneeId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 15, 46, 22, 586, DateTimeKind.Unspecified).AddTicks(2612),
                            DateShipped = new DateTime(2021, 6, 15, 2, 47, 19, 21, DateTimeKind.Unspecified).AddTicks(9556)
                        });
                });

            modelBuilder.Entity("ConsignorManifest", b =>
                {
                    b.HasOne("EPManifest.Core.Consignor", null)
                        .WithMany()
                        .HasForeignKey("ConsignorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Manifest", null)
                        .WithMany()
                        .HasForeignKey("ManifestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.HasOne("EPManifest.Core.Manifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.HasOne("EPManifest.Core.Carrier", "Carrier")
                        .WithMany("Manifests")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Consignee", "Consignee")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EPManifest.Core.Address", "ConsigneeAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsigneeAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.OwnsOne("EPManifest.Core.Address", "ConsignorAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsignorAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeAddress");

                    b.Navigation("ConsignorAddress");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
