// <auto-generated />
using System;
using EPManifest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPManifest.Data.Migrations
{
    [DbContext(typeof(EPManifestDbContext))]
    [Migration("20210517014846_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1 Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pacific Northwest Freight"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AP Freight"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NM Shipping Inc"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frank's Freight"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pete's Disposal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATI Environmental"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EQ Enviro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Whitehorse Landfill"
                        },
                        new
                        {
                            Id = 5,
                            Name = "YAE"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carmacks Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mayo Health Centre"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whitehorse General Hospital"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Teslin Health Centre"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whistle Bend Place"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<int>("ConsignorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShipped")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ConsignorId");

                    b.ToTable("Manifests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 20, 7, 37, 19, 546, DateTimeKind.Unspecified).AddTicks(93),
                            DateShipped = new DateTime(2021, 7, 28, 21, 6, 35, 778, DateTimeKind.Unspecified).AddTicks(2548)
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 30, 23, 5, 38, 489, DateTimeKind.Unspecified).AddTicks(5861),
                            DateShipped = new DateTime(2021, 6, 13, 17, 26, 56, 756, DateTimeKind.Unspecified).AddTicks(9945)
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 18, 2, 53, 10, 50, DateTimeKind.Unspecified).AddTicks(9510),
                            DateShipped = new DateTime(2021, 8, 1, 9, 51, 50, 337, DateTimeKind.Unspecified).AddTicks(4810)
                        },
                        new
                        {
                            Id = 4,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 10, 15, 35, 425, DateTimeKind.Unspecified).AddTicks(245),
                            DateShipped = new DateTime(2021, 5, 8, 13, 29, 50, 426, DateTimeKind.Unspecified).AddTicks(6688)
                        },
                        new
                        {
                            Id = 5,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 4, 6, 40, 57, 833, DateTimeKind.Unspecified).AddTicks(1895),
                            DateShipped = new DateTime(2021, 5, 22, 9, 55, 46, 230, DateTimeKind.Unspecified).AddTicks(2672)
                        },
                        new
                        {
                            Id = 6,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 30, 23, 58, 20, 123, DateTimeKind.Unspecified).AddTicks(8167),
                            DateShipped = new DateTime(2021, 7, 12, 17, 25, 49, 897, DateTimeKind.Unspecified).AddTicks(4496)
                        },
                        new
                        {
                            Id = 7,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 5, 14, 52, 258, DateTimeKind.Unspecified).AddTicks(1478),
                            DateShipped = new DateTime(2021, 6, 15, 6, 14, 31, 21, DateTimeKind.Unspecified).AddTicks(3170)
                        },
                        new
                        {
                            Id = 8,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 13, 46, 4, 555, DateTimeKind.Unspecified).AddTicks(2821),
                            DateShipped = new DateTime(2021, 7, 3, 14, 15, 41, 665, DateTimeKind.Unspecified).AddTicks(9415)
                        },
                        new
                        {
                            Id = 9,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 21, 4, 20, 48, 534, DateTimeKind.Unspecified).AddTicks(8834),
                            DateShipped = new DateTime(2021, 8, 18, 7, 6, 20, 247, DateTimeKind.Unspecified).AddTicks(3426)
                        },
                        new
                        {
                            Id = 10,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 22, 10, 50, 52, 758, DateTimeKind.Unspecified).AddTicks(4213),
                            DateShipped = new DateTime(2021, 8, 5, 15, 5, 24, 978, DateTimeKind.Unspecified).AddTicks(6287)
                        },
                        new
                        {
                            Id = 11,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 31, 23, 13, 18, 102, DateTimeKind.Unspecified).AddTicks(7441),
                            DateShipped = new DateTime(2021, 7, 8, 3, 42, 55, 672, DateTimeKind.Unspecified).AddTicks(2960)
                        },
                        new
                        {
                            Id = 12,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 7, 28, 39, 972, DateTimeKind.Unspecified).AddTicks(8868),
                            DateShipped = new DateTime(2021, 8, 23, 6, 37, 34, 862, DateTimeKind.Unspecified).AddTicks(4135)
                        },
                        new
                        {
                            Id = 13,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 26, 8, 29, 59, 230, DateTimeKind.Unspecified).AddTicks(3007),
                            DateShipped = new DateTime(2021, 6, 13, 17, 28, 31, 680, DateTimeKind.Unspecified).AddTicks(6398)
                        },
                        new
                        {
                            Id = 14,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 7, 15, 7, 6, 603, DateTimeKind.Unspecified).AddTicks(222),
                            DateShipped = new DateTime(2021, 5, 15, 6, 27, 47, 282, DateTimeKind.Unspecified).AddTicks(2167)
                        },
                        new
                        {
                            Id = 15,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 3, 1, 0, 2, 838, DateTimeKind.Unspecified).AddTicks(3957),
                            DateShipped = new DateTime(2021, 6, 8, 9, 8, 21, 799, DateTimeKind.Unspecified).AddTicks(7478)
                        },
                        new
                        {
                            Id = 16,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 1, 8, 42, 45, 65, DateTimeKind.Unspecified).AddTicks(1333),
                            DateShipped = new DateTime(2021, 6, 29, 6, 11, 41, 754, DateTimeKind.Unspecified).AddTicks(9648)
                        },
                        new
                        {
                            Id = 17,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 4, 9, 52, 55, 154, DateTimeKind.Unspecified).AddTicks(8724),
                            DateShipped = new DateTime(2021, 5, 24, 19, 48, 52, 812, DateTimeKind.Unspecified).AddTicks(9996)
                        },
                        new
                        {
                            Id = 18,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 5, 22, 21, 47, 443, DateTimeKind.Unspecified).AddTicks(7069),
                            DateShipped = new DateTime(2021, 8, 11, 7, 34, 36, 130, DateTimeKind.Unspecified).AddTicks(2792)
                        },
                        new
                        {
                            Id = 19,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 6, 11, 48, 821, DateTimeKind.Unspecified).AddTicks(5127),
                            DateShipped = new DateTime(2021, 7, 27, 1, 24, 9, 129, DateTimeKind.Unspecified).AddTicks(7269)
                        },
                        new
                        {
                            Id = 20,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 25, 22, 20, 35, 220, DateTimeKind.Unspecified).AddTicks(391),
                            DateShipped = new DateTime(2021, 7, 25, 4, 46, 45, 772, DateTimeKind.Unspecified).AddTicks(2634)
                        },
                        new
                        {
                            Id = 21,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 18, 32, 43, 110, DateTimeKind.Unspecified).AddTicks(831),
                            DateShipped = new DateTime(2021, 7, 30, 7, 51, 43, 0, DateTimeKind.Unspecified).AddTicks(5497)
                        },
                        new
                        {
                            Id = 22,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 11, 0, 52, 82, DateTimeKind.Unspecified).AddTicks(8715),
                            DateShipped = new DateTime(2021, 5, 9, 5, 44, 22, 230, DateTimeKind.Unspecified).AddTicks(8455)
                        },
                        new
                        {
                            Id = 23,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 11, 58, 36, 297, DateTimeKind.Unspecified).AddTicks(5572),
                            DateShipped = new DateTime(2021, 5, 28, 10, 38, 36, 164, DateTimeKind.Unspecified).AddTicks(1463)
                        },
                        new
                        {
                            Id = 24,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 19, 13, 25, 15, 477, DateTimeKind.Unspecified).AddTicks(6873),
                            DateShipped = new DateTime(2021, 7, 8, 23, 57, 4, 549, DateTimeKind.Unspecified).AddTicks(9759)
                        },
                        new
                        {
                            Id = 25,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 14, 0, 12, 603, DateTimeKind.Unspecified).AddTicks(5091),
                            DateShipped = new DateTime(2021, 7, 6, 14, 33, 51, 281, DateTimeKind.Unspecified).AddTicks(9993)
                        },
                        new
                        {
                            Id = 26,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 14, 12, 54, 649, DateTimeKind.Unspecified).AddTicks(5068),
                            DateShipped = new DateTime(2021, 8, 26, 23, 16, 58, 209, DateTimeKind.Unspecified).AddTicks(539)
                        },
                        new
                        {
                            Id = 27,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 5, 21, 31, 53, 41, DateTimeKind.Unspecified).AddTicks(2388),
                            DateShipped = new DateTime(2021, 7, 4, 1, 49, 9, 273, DateTimeKind.Unspecified).AddTicks(1095)
                        },
                        new
                        {
                            Id = 28,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 28, 17, 6, 29, 104, DateTimeKind.Unspecified).AddTicks(7914),
                            DateShipped = new DateTime(2021, 6, 25, 9, 43, 34, 154, DateTimeKind.Unspecified).AddTicks(6561)
                        },
                        new
                        {
                            Id = 29,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 1, 3, 31, 44, 274, DateTimeKind.Unspecified).AddTicks(2073),
                            DateShipped = new DateTime(2021, 8, 6, 3, 3, 31, 753, DateTimeKind.Unspecified).AddTicks(9964)
                        },
                        new
                        {
                            Id = 30,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 16, 59, 52, 269, DateTimeKind.Unspecified).AddTicks(8485),
                            DateShipped = new DateTime(2021, 5, 9, 15, 36, 23, 227, DateTimeKind.Unspecified).AddTicks(899)
                        },
                        new
                        {
                            Id = 31,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 2, 8, 26, 48, 789, DateTimeKind.Unspecified).AddTicks(4507),
                            DateShipped = new DateTime(2021, 8, 5, 1, 44, 34, 533, DateTimeKind.Unspecified).AddTicks(1391)
                        },
                        new
                        {
                            Id = 32,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 6, 50, 18, 766, DateTimeKind.Unspecified).AddTicks(9004),
                            DateShipped = new DateTime(2021, 8, 29, 4, 28, 12, 674, DateTimeKind.Unspecified).AddTicks(9006)
                        },
                        new
                        {
                            Id = 33,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 17, 53, 57, 871, DateTimeKind.Unspecified).AddTicks(3967),
                            DateShipped = new DateTime(2021, 5, 27, 16, 25, 39, 216, DateTimeKind.Unspecified).AddTicks(8514)
                        },
                        new
                        {
                            Id = 34,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 4, 22, 26, 59, DateTimeKind.Unspecified).AddTicks(2388),
                            DateShipped = new DateTime(2021, 8, 18, 6, 38, 32, 860, DateTimeKind.Unspecified).AddTicks(4896)
                        },
                        new
                        {
                            Id = 35,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 16, 1, 55, 11, 484, DateTimeKind.Unspecified).AddTicks(6232),
                            DateShipped = new DateTime(2021, 6, 12, 15, 49, 25, 483, DateTimeKind.Unspecified).AddTicks(4387)
                        },
                        new
                        {
                            Id = 36,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 15, 18, 11, 47, 505, DateTimeKind.Unspecified).AddTicks(2253),
                            DateShipped = new DateTime(2021, 8, 3, 23, 30, 28, 46, DateTimeKind.Unspecified).AddTicks(1825)
                        },
                        new
                        {
                            Id = 37,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 27, 16, 48, 12, 929, DateTimeKind.Unspecified).AddTicks(1232),
                            DateShipped = new DateTime(2021, 8, 6, 8, 7, 10, 514, DateTimeKind.Unspecified).AddTicks(5698)
                        },
                        new
                        {
                            Id = 38,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 10, 13, 30, 47, 132, DateTimeKind.Unspecified).AddTicks(140),
                            DateShipped = new DateTime(2021, 7, 31, 7, 16, 43, 729, DateTimeKind.Unspecified).AddTicks(4167)
                        },
                        new
                        {
                            Id = 39,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 22, 39, 21, 564, DateTimeKind.Unspecified).AddTicks(8456),
                            DateShipped = new DateTime(2021, 8, 1, 4, 48, 48, 549, DateTimeKind.Unspecified).AddTicks(7508)
                        },
                        new
                        {
                            Id = 40,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 16, 16, 1, 21, 519, DateTimeKind.Unspecified).AddTicks(1850),
                            DateShipped = new DateTime(2021, 7, 26, 21, 56, 52, 124, DateTimeKind.Unspecified).AddTicks(1565)
                        },
                        new
                        {
                            Id = 41,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 6, 43, 58, 708, DateTimeKind.Unspecified).AddTicks(6519),
                            DateShipped = new DateTime(2021, 8, 27, 17, 23, 59, 451, DateTimeKind.Unspecified).AddTicks(7803)
                        },
                        new
                        {
                            Id = 42,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 21, 15, 45, 42, 204, DateTimeKind.Unspecified).AddTicks(6255),
                            DateShipped = new DateTime(2021, 8, 19, 6, 4, 1, 303, DateTimeKind.Unspecified).AddTicks(9518)
                        },
                        new
                        {
                            Id = 43,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 17, 0, 0, 11, 56, DateTimeKind.Unspecified).AddTicks(8300),
                            DateShipped = new DateTime(2021, 5, 20, 16, 8, 4, 715, DateTimeKind.Unspecified).AddTicks(3889)
                        },
                        new
                        {
                            Id = 44,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 6, 17, 53, 25, 369, DateTimeKind.Unspecified).AddTicks(3401),
                            DateShipped = new DateTime(2021, 5, 30, 19, 41, 48, 747, DateTimeKind.Unspecified).AddTicks(236)
                        },
                        new
                        {
                            Id = 45,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 22, 22, 51, 9, 508, DateTimeKind.Unspecified).AddTicks(1394),
                            DateShipped = new DateTime(2021, 8, 9, 4, 30, 36, 660, DateTimeKind.Unspecified).AddTicks(6415)
                        },
                        new
                        {
                            Id = 46,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 13, 15, 42, 30, 153, DateTimeKind.Unspecified).AddTicks(5247),
                            DateShipped = new DateTime(2021, 8, 30, 14, 19, 27, 301, DateTimeKind.Unspecified).AddTicks(9739)
                        },
                        new
                        {
                            Id = 47,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 8, 5, 3, 4, 660, DateTimeKind.Unspecified).AddTicks(4968),
                            DateShipped = new DateTime(2021, 8, 17, 14, 25, 42, 304, DateTimeKind.Unspecified).AddTicks(8082)
                        },
                        new
                        {
                            Id = 48,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 15, 52, 8, 992, DateTimeKind.Unspecified).AddTicks(671),
                            DateShipped = new DateTime(2021, 5, 14, 10, 26, 51, 907, DateTimeKind.Unspecified).AddTicks(1733)
                        },
                        new
                        {
                            Id = 49,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 8, 19, 20, 794, DateTimeKind.Unspecified).AddTicks(3347),
                            DateShipped = new DateTime(2021, 8, 9, 4, 23, 52, 212, DateTimeKind.Unspecified).AddTicks(6239)
                        },
                        new
                        {
                            Id = 50,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 15, 46, 23, 916, DateTimeKind.Unspecified).AddTicks(4089),
                            DateShipped = new DateTime(2021, 7, 16, 23, 51, 6, 801, DateTimeKind.Unspecified).AddTicks(5239)
                        },
                        new
                        {
                            Id = 51,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 12, 42, 18, 561, DateTimeKind.Unspecified).AddTicks(6292),
                            DateShipped = new DateTime(2021, 6, 22, 22, 35, 50, 822, DateTimeKind.Unspecified).AddTicks(7176)
                        },
                        new
                        {
                            Id = 52,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 14, 1, 10, 0, 512, DateTimeKind.Unspecified).AddTicks(5632),
                            DateShipped = new DateTime(2021, 7, 9, 8, 22, 28, 596, DateTimeKind.Unspecified).AddTicks(9371)
                        },
                        new
                        {
                            Id = 53,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 29, 19, 37, 40, 629, DateTimeKind.Unspecified).AddTicks(6406),
                            DateShipped = new DateTime(2021, 6, 10, 6, 0, 49, 9, DateTimeKind.Unspecified).AddTicks(2796)
                        },
                        new
                        {
                            Id = 54,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 23, 36, 8, 369, DateTimeKind.Unspecified).AddTicks(1003),
                            DateShipped = new DateTime(2021, 7, 9, 20, 15, 34, 4, DateTimeKind.Unspecified).AddTicks(9994)
                        },
                        new
                        {
                            Id = 55,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 30, 7, 20, 21, 110, DateTimeKind.Unspecified).AddTicks(120),
                            DateShipped = new DateTime(2021, 7, 15, 18, 18, 2, 19, DateTimeKind.Unspecified).AddTicks(260)
                        },
                        new
                        {
                            Id = 56,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 5, 30, 37, 522, DateTimeKind.Unspecified).AddTicks(5845),
                            DateShipped = new DateTime(2021, 8, 27, 20, 47, 55, 575, DateTimeKind.Unspecified).AddTicks(1169)
                        },
                        new
                        {
                            Id = 57,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 18, 10, 16, 738, DateTimeKind.Unspecified).AddTicks(7894),
                            DateShipped = new DateTime(2021, 8, 10, 0, 19, 29, 364, DateTimeKind.Unspecified).AddTicks(8910)
                        },
                        new
                        {
                            Id = 58,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 23, 17, 11, 55, 843, DateTimeKind.Unspecified).AddTicks(4739),
                            DateShipped = new DateTime(2021, 8, 12, 8, 18, 13, 258, DateTimeKind.Unspecified).AddTicks(6317)
                        },
                        new
                        {
                            Id = 59,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 17, 20, 42, 50, 793, DateTimeKind.Unspecified).AddTicks(7081),
                            DateShipped = new DateTime(2021, 5, 30, 13, 6, 26, 626, DateTimeKind.Unspecified).AddTicks(6381)
                        },
                        new
                        {
                            Id = 60,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 24, 22, 42, 0, 921, DateTimeKind.Unspecified).AddTicks(9374),
                            DateShipped = new DateTime(2021, 7, 12, 19, 3, 55, 746, DateTimeKind.Unspecified).AddTicks(4365)
                        },
                        new
                        {
                            Id = 61,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 14, 0, 25, 6, 289, DateTimeKind.Unspecified).AddTicks(7183),
                            DateShipped = new DateTime(2021, 5, 29, 12, 55, 26, 616, DateTimeKind.Unspecified).AddTicks(153)
                        },
                        new
                        {
                            Id = 62,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 21, 6, 54, 46, 293, DateTimeKind.Unspecified).AddTicks(1904),
                            DateShipped = new DateTime(2021, 7, 22, 2, 43, 46, 627, DateTimeKind.Unspecified).AddTicks(2516)
                        },
                        new
                        {
                            Id = 63,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 29, 15, 44, 14, 348, DateTimeKind.Unspecified).AddTicks(2925),
                            DateShipped = new DateTime(2021, 6, 19, 4, 7, 45, 1, DateTimeKind.Unspecified).AddTicks(923)
                        },
                        new
                        {
                            Id = 64,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 6, 20, 37, 29, 161, DateTimeKind.Unspecified).AddTicks(2944),
                            DateShipped = new DateTime(2021, 7, 26, 2, 25, 45, 497, DateTimeKind.Unspecified).AddTicks(2069)
                        },
                        new
                        {
                            Id = 65,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 15, 0, 2, 27, 364, DateTimeKind.Unspecified).AddTicks(7610),
                            DateShipped = new DateTime(2021, 8, 14, 6, 41, 25, 62, DateTimeKind.Unspecified).AddTicks(8548)
                        },
                        new
                        {
                            Id = 66,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 2, 22, 5, 49, 492, DateTimeKind.Unspecified).AddTicks(1131),
                            DateShipped = new DateTime(2021, 6, 1, 5, 21, 26, 636, DateTimeKind.Unspecified).AddTicks(5761)
                        },
                        new
                        {
                            Id = 67,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 12, 27, 33, 737, DateTimeKind.Unspecified).AddTicks(6210),
                            DateShipped = new DateTime(2021, 7, 7, 14, 17, 54, 698, DateTimeKind.Unspecified).AddTicks(8953)
                        },
                        new
                        {
                            Id = 68,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 9, 59, 32, 787, DateTimeKind.Unspecified).AddTicks(5579),
                            DateShipped = new DateTime(2021, 8, 26, 3, 41, 44, 709, DateTimeKind.Unspecified).AddTicks(3736)
                        },
                        new
                        {
                            Id = 69,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 5, 16, 37, 39, 765, DateTimeKind.Unspecified).AddTicks(5083),
                            DateShipped = new DateTime(2021, 5, 27, 2, 7, 49, 95, DateTimeKind.Unspecified).AddTicks(6822)
                        },
                        new
                        {
                            Id = 70,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 14, 0, 38, 35, 424, DateTimeKind.Unspecified).AddTicks(7384),
                            DateShipped = new DateTime(2021, 8, 26, 7, 28, 21, 915, DateTimeKind.Unspecified).AddTicks(4510)
                        },
                        new
                        {
                            Id = 71,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 29, 1, 39, 34, 916, DateTimeKind.Unspecified).AddTicks(2970),
                            DateShipped = new DateTime(2021, 6, 8, 17, 6, 58, 774, DateTimeKind.Unspecified).AddTicks(9583)
                        },
                        new
                        {
                            Id = 72,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 25, 5, 44, 50, 431, DateTimeKind.Unspecified).AddTicks(8593),
                            DateShipped = new DateTime(2021, 7, 12, 6, 8, 28, 872, DateTimeKind.Unspecified).AddTicks(6474)
                        },
                        new
                        {
                            Id = 73,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 23, 1, 48, 5, 549, DateTimeKind.Unspecified).AddTicks(3352),
                            DateShipped = new DateTime(2021, 6, 21, 18, 37, 14, 961, DateTimeKind.Unspecified).AddTicks(1937)
                        },
                        new
                        {
                            Id = 74,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 15, 31, 59, 655, DateTimeKind.Unspecified).AddTicks(4355),
                            DateShipped = new DateTime(2021, 5, 14, 12, 19, 14, 424, DateTimeKind.Unspecified).AddTicks(145)
                        },
                        new
                        {
                            Id = 75,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 13, 50, 14, 120, DateTimeKind.Unspecified).AddTicks(4544),
                            DateShipped = new DateTime(2021, 6, 18, 15, 20, 44, 87, DateTimeKind.Unspecified).AddTicks(5445)
                        },
                        new
                        {
                            Id = 76,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 13, 20, 48, 10, 772, DateTimeKind.Unspecified).AddTicks(572),
                            DateShipped = new DateTime(2021, 8, 9, 19, 38, 50, 740, DateTimeKind.Unspecified).AddTicks(2642)
                        },
                        new
                        {
                            Id = 77,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 4, 17, 30, 41, 722, DateTimeKind.Unspecified).AddTicks(9037),
                            DateShipped = new DateTime(2021, 5, 19, 20, 13, 1, 894, DateTimeKind.Unspecified).AddTicks(561)
                        },
                        new
                        {
                            Id = 78,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 2, 15, 56, 9, 175, DateTimeKind.Unspecified).AddTicks(6769),
                            DateShipped = new DateTime(2021, 7, 9, 10, 20, 27, 464, DateTimeKind.Unspecified).AddTicks(3982)
                        },
                        new
                        {
                            Id = 79,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 6, 18, 6, 631, DateTimeKind.Unspecified).AddTicks(5739),
                            DateShipped = new DateTime(2021, 8, 3, 2, 47, 43, 389, DateTimeKind.Unspecified).AddTicks(8380)
                        },
                        new
                        {
                            Id = 80,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 21, 12, 58, 31, 921, DateTimeKind.Unspecified).AddTicks(6287),
                            DateShipped = new DateTime(2021, 8, 29, 2, 35, 59, 689, DateTimeKind.Unspecified).AddTicks(2892)
                        },
                        new
                        {
                            Id = 81,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 10, 23, 54, 44, 450, DateTimeKind.Unspecified).AddTicks(6754),
                            DateShipped = new DateTime(2021, 7, 10, 3, 1, 25, 714, DateTimeKind.Unspecified).AddTicks(40)
                        },
                        new
                        {
                            Id = 82,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 18, 37, 1, 694, DateTimeKind.Unspecified).AddTicks(5588),
                            DateShipped = new DateTime(2021, 7, 8, 13, 52, 57, 255, DateTimeKind.Unspecified).AddTicks(5182)
                        },
                        new
                        {
                            Id = 83,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 3, 5, 47, 28, 912, DateTimeKind.Unspecified).AddTicks(4321),
                            DateShipped = new DateTime(2021, 8, 26, 1, 14, 45, 411, DateTimeKind.Unspecified).AddTicks(6014)
                        },
                        new
                        {
                            Id = 84,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 8, 22, 34, 23, 192, DateTimeKind.Unspecified).AddTicks(9374),
                            DateShipped = new DateTime(2021, 5, 20, 17, 15, 1, 92, DateTimeKind.Unspecified).AddTicks(3183)
                        },
                        new
                        {
                            Id = 85,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 2, 22, 35, 20, 84, DateTimeKind.Unspecified).AddTicks(8437),
                            DateShipped = new DateTime(2021, 8, 7, 10, 4, 3, 223, DateTimeKind.Unspecified).AddTicks(9910)
                        },
                        new
                        {
                            Id = 86,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 11, 41, 22, 539, DateTimeKind.Unspecified).AddTicks(4946),
                            DateShipped = new DateTime(2021, 7, 12, 3, 36, 14, 974, DateTimeKind.Unspecified).AddTicks(8916)
                        },
                        new
                        {
                            Id = 87,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 12, 14, 49, 26, 756, DateTimeKind.Unspecified).AddTicks(7889),
                            DateShipped = new DateTime(2021, 5, 24, 7, 42, 43, 211, DateTimeKind.Unspecified).AddTicks(4435)
                        },
                        new
                        {
                            Id = 88,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 12, 49, 27, 449, DateTimeKind.Unspecified).AddTicks(1039),
                            DateShipped = new DateTime(2021, 5, 10, 8, 12, 4, 771, DateTimeKind.Unspecified).AddTicks(5134)
                        },
                        new
                        {
                            Id = 89,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 14, 12, 57, 41, 136, DateTimeKind.Unspecified).AddTicks(5491),
                            DateShipped = new DateTime(2021, 6, 24, 10, 29, 53, 622, DateTimeKind.Unspecified).AddTicks(4622)
                        },
                        new
                        {
                            Id = 90,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 18, 7, 9, 55, 864, DateTimeKind.Unspecified).AddTicks(6000),
                            DateShipped = new DateTime(2021, 7, 31, 23, 40, 16, 902, DateTimeKind.Unspecified).AddTicks(8157)
                        },
                        new
                        {
                            Id = 91,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 13, 21, 21, 27, 851, DateTimeKind.Unspecified).AddTicks(7509),
                            DateShipped = new DateTime(2021, 5, 27, 1, 46, 27, 233, DateTimeKind.Unspecified).AddTicks(1917)
                        },
                        new
                        {
                            Id = 92,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 30, 0, 31, 48, 68, DateTimeKind.Unspecified).AddTicks(3881),
                            DateShipped = new DateTime(2021, 8, 5, 19, 2, 33, 401, DateTimeKind.Unspecified).AddTicks(9626)
                        },
                        new
                        {
                            Id = 93,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 3, 14, 40, 40, 895, DateTimeKind.Unspecified).AddTicks(8309),
                            DateShipped = new DateTime(2021, 5, 22, 13, 5, 12, 32, DateTimeKind.Unspecified).AddTicks(316)
                        },
                        new
                        {
                            Id = 94,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 16, 45, 24, 201, DateTimeKind.Unspecified).AddTicks(6134),
                            DateShipped = new DateTime(2021, 5, 20, 12, 32, 43, 287, DateTimeKind.Unspecified).AddTicks(3805)
                        },
                        new
                        {
                            Id = 95,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 3, 20, 3, 25, 824, DateTimeKind.Unspecified).AddTicks(5593),
                            DateShipped = new DateTime(2021, 7, 27, 15, 22, 33, 516, DateTimeKind.Unspecified).AddTicks(7237)
                        },
                        new
                        {
                            Id = 96,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 14, 12, 58, 17, 205, DateTimeKind.Unspecified).AddTicks(4341),
                            DateShipped = new DateTime(2021, 7, 25, 13, 13, 11, 730, DateTimeKind.Unspecified).AddTicks(5766)
                        },
                        new
                        {
                            Id = 97,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 13, 4, 12, 27, 814, DateTimeKind.Unspecified).AddTicks(22),
                            DateShipped = new DateTime(2021, 5, 28, 4, 43, 40, 227, DateTimeKind.Unspecified).AddTicks(5445)
                        },
                        new
                        {
                            Id = 98,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 15, 51, 59, 761, DateTimeKind.Unspecified).AddTicks(167),
                            DateShipped = new DateTime(2021, 8, 6, 13, 23, 48, 476, DateTimeKind.Unspecified).AddTicks(3084)
                        },
                        new
                        {
                            Id = 99,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 19, 7, 47, 392, DateTimeKind.Unspecified).AddTicks(1325),
                            DateShipped = new DateTime(2021, 7, 8, 5, 54, 44, 871, DateTimeKind.Unspecified).AddTicks(8057)
                        },
                        new
                        {
                            Id = 100,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 11, 3, 14, 43, 705, DateTimeKind.Unspecified).AddTicks(2906),
                            DateShipped = new DateTime(2021, 7, 20, 11, 13, 32, 605, DateTimeKind.Unspecified).AddTicks(7634)
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.HasOne("EPManifest.Core.Manifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.HasOne("EPManifest.Core.Carrier", "Carrier")
                        .WithMany("Manifests")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Consignee", "Consignee")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EPManifest.Core.Consignor", "Consignor")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsignorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EPManifest.Core.Address", "ConsigneeAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsigneeAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.OwnsOne("EPManifest.Core.Address", "ConsignorAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsignorAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeAddress");

                    b.Navigation("Consignor");

                    b.Navigation("ConsignorAddress");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
