// <auto-generated />
using System;
using EPManifest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPManifest.Data.Migrations
{
    [DbContext(typeof(EPManifestDbContext))]
    [Migration("20210512045842_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1 Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pacific Northwest Freight"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AP Freight"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NM Shipping Inc"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frank's Freight"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pete's Disposal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATI Environmental"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EQ Enviro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Whitehorse Landfill"
                        },
                        new
                        {
                            Id = 5,
                            Name = "YAE"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carmacks Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mayo Health Centre"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whitehorse General Hospital"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Teslin Health Centre"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whistlebend Care Home"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsignorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateShipped")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ConsignorId");

                    b.ToTable("Manifests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 5, 14, 21, 40, 42, 29, DateTimeKind.Local).AddTicks(5585),
                            DateShipped = new DateTime(2021, 10, 4, 14, 58, 16, 385, DateTimeKind.Local).AddTicks(3899)
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 17, 30, 45, 363, DateTimeKind.Local).AddTicks(8552),
                            DateShipped = new DateTime(2021, 8, 3, 10, 35, 2, 330, DateTimeKind.Local).AddTicks(2739)
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 25, 16, 24, 2, 84, DateTimeKind.Local).AddTicks(1093),
                            DateShipped = new DateTime(2021, 10, 24, 18, 51, 36, 133, DateTimeKind.Local).AddTicks(2135)
                        },
                        new
                        {
                            Id = 4,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 8, 31, 21, 26, 34, 352, DateTimeKind.Local).AddTicks(897),
                            DateShipped = new DateTime(2021, 9, 27, 12, 58, 34, 627, DateTimeKind.Local).AddTicks(2520)
                        },
                        new
                        {
                            Id = 5,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 6, 25, 1, 3, 11, 909, DateTimeKind.Local).AddTicks(7247),
                            DateShipped = new DateTime(2021, 12, 29, 13, 24, 39, 760, DateTimeKind.Local).AddTicks(1115)
                        },
                        new
                        {
                            Id = 6,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 8, 30, 38, 160, DateTimeKind.Local).AddTicks(8027),
                            DateShipped = new DateTime(2021, 12, 7, 19, 27, 4, 7, DateTimeKind.Local).AddTicks(3144)
                        },
                        new
                        {
                            Id = 7,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 15, 3, 14, 30, 382, DateTimeKind.Local).AddTicks(7575),
                            DateShipped = new DateTime(2021, 8, 14, 12, 51, 49, 513, DateTimeKind.Local).AddTicks(4816)
                        },
                        new
                        {
                            Id = 8,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 17, 19, 5, 29, 232, DateTimeKind.Local).AddTicks(9544),
                            DateShipped = new DateTime(2021, 10, 24, 20, 28, 11, 117, DateTimeKind.Local).AddTicks(820)
                        },
                        new
                        {
                            Id = 9,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 7, 16, 9, 53, 8, 336, DateTimeKind.Local).AddTicks(4709),
                            DateShipped = new DateTime(2021, 6, 7, 8, 43, 44, 701, DateTimeKind.Local).AddTicks(8986)
                        },
                        new
                        {
                            Id = 10,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 7, 9, 47, 54, 383, DateTimeKind.Local).AddTicks(3357),
                            DateShipped = new DateTime(2021, 7, 25, 10, 31, 21, 701, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            Id = 11,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 8, 6, 17, 30, 34, 312, DateTimeKind.Local).AddTicks(3879),
                            DateShipped = new DateTime(2021, 7, 26, 22, 35, 13, 448, DateTimeKind.Local).AddTicks(1438)
                        },
                        new
                        {
                            Id = 12,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 12, 45, 12, 532, DateTimeKind.Local).AddTicks(402),
                            DateShipped = new DateTime(2021, 8, 21, 11, 53, 46, 209, DateTimeKind.Local).AddTicks(5791)
                        },
                        new
                        {
                            Id = 13,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 7, 20, 3, 20, 59, 831, DateTimeKind.Local).AddTicks(2925),
                            DateShipped = new DateTime(2021, 8, 24, 2, 4, 24, 169, DateTimeKind.Local).AddTicks(5096)
                        },
                        new
                        {
                            Id = 14,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 7, 14, 9, 49, 28, 813, DateTimeKind.Local).AddTicks(8180),
                            DateShipped = new DateTime(2021, 11, 9, 15, 37, 5, 750, DateTimeKind.Local).AddTicks(4726)
                        },
                        new
                        {
                            Id = 15,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 5, 12, 8, 19, 52, 568, DateTimeKind.Local).AddTicks(1452),
                            DateShipped = new DateTime(2021, 5, 21, 15, 51, 47, 127, DateTimeKind.Local).AddTicks(3125)
                        },
                        new
                        {
                            Id = 16,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 4, 2, 58, 28, 507, DateTimeKind.Local).AddTicks(500),
                            DateShipped = new DateTime(2021, 10, 25, 1, 30, 13, 156, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            Id = 17,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 6, 22, 21, 15, 2, 244, DateTimeKind.Local).AddTicks(8409),
                            DateShipped = new DateTime(2021, 7, 12, 7, 37, 51, 356, DateTimeKind.Local).AddTicks(9748)
                        },
                        new
                        {
                            Id = 18,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 7, 27, 18, 6, 0, 164, DateTimeKind.Local).AddTicks(9097),
                            DateShipped = new DateTime(2021, 5, 19, 17, 19, 56, 934, DateTimeKind.Local).AddTicks(966)
                        },
                        new
                        {
                            Id = 19,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 8, 9, 19, 48, 45, 904, DateTimeKind.Local).AddTicks(9286),
                            DateShipped = new DateTime(2021, 5, 26, 5, 41, 40, 318, DateTimeKind.Local).AddTicks(439)
                        },
                        new
                        {
                            Id = 20,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 7, 27, 8, 38, 16, 572, DateTimeKind.Local).AddTicks(1297),
                            DateShipped = new DateTime(2021, 11, 18, 5, 22, 44, 870, DateTimeKind.Local).AddTicks(6133)
                        },
                        new
                        {
                            Id = 21,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 7, 10, 1, 26, 52, 622, DateTimeKind.Local).AddTicks(2719),
                            DateShipped = new DateTime(2021, 5, 22, 22, 40, 34, 620, DateTimeKind.Local).AddTicks(7925)
                        },
                        new
                        {
                            Id = 22,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 15, 12, 24, 9, 982, DateTimeKind.Local).AddTicks(4806),
                            DateShipped = new DateTime(2021, 7, 26, 12, 14, 2, 613, DateTimeKind.Local).AddTicks(49)
                        },
                        new
                        {
                            Id = 23,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 2, 21, 45, 52, 25, DateTimeKind.Local).AddTicks(7051),
                            DateShipped = new DateTime(2021, 11, 17, 8, 55, 17, 702, DateTimeKind.Local).AddTicks(5359)
                        },
                        new
                        {
                            Id = 24,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 8, 43, 7, 849, DateTimeKind.Local).AddTicks(7558),
                            DateShipped = new DateTime(2021, 7, 13, 2, 48, 3, 657, DateTimeKind.Local).AddTicks(6843)
                        },
                        new
                        {
                            Id = 25,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 14, 22, 40, 20, 194, DateTimeKind.Local).AddTicks(1599),
                            DateShipped = new DateTime(2021, 8, 24, 19, 29, 47, 318, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            Id = 26,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 14, 2, 42, 14, 828, DateTimeKind.Local).AddTicks(917),
                            DateShipped = new DateTime(2021, 10, 11, 20, 3, 1, 222, DateTimeKind.Local).AddTicks(3961)
                        },
                        new
                        {
                            Id = 27,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 8, 15, 10, 14, 48, 253, DateTimeKind.Local).AddTicks(6273),
                            DateShipped = new DateTime(2021, 8, 9, 14, 50, 38, 317, DateTimeKind.Local).AddTicks(5167)
                        },
                        new
                        {
                            Id = 28,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 12, 5, 14, 5, 343, DateTimeKind.Local).AddTicks(7110),
                            DateShipped = new DateTime(2021, 5, 14, 4, 9, 40, 467, DateTimeKind.Local).AddTicks(7302)
                        },
                        new
                        {
                            Id = 29,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 7, 7, 21, 27, 30, 744, DateTimeKind.Local).AddTicks(4016),
                            DateShipped = new DateTime(2021, 8, 4, 4, 55, 46, 951, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            Id = 30,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 7, 13, 6, 26, 46, 524, DateTimeKind.Local).AddTicks(5843),
                            DateShipped = new DateTime(2021, 7, 23, 7, 55, 48, 292, DateTimeKind.Local).AddTicks(3598)
                        },
                        new
                        {
                            Id = 31,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 1, 4, 39, 7, 49, DateTimeKind.Local).AddTicks(156),
                            DateShipped = new DateTime(2021, 7, 18, 18, 38, 18, 753, DateTimeKind.Local).AddTicks(8848)
                        },
                        new
                        {
                            Id = 32,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 5, 29, 0, 33, 20, 881, DateTimeKind.Local).AddTicks(7517),
                            DateShipped = new DateTime(2021, 7, 8, 0, 0, 14, 426, DateTimeKind.Local).AddTicks(6543)
                        },
                        new
                        {
                            Id = 33,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 6, 22, 2, 26, 19, 41, DateTimeKind.Local).AddTicks(6606),
                            DateShipped = new DateTime(2021, 10, 12, 9, 31, 47, 784, DateTimeKind.Local).AddTicks(9268)
                        },
                        new
                        {
                            Id = 34,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 5, 15, 0, 9, 3, 127, DateTimeKind.Local).AddTicks(1997),
                            DateShipped = new DateTime(2021, 8, 13, 20, 39, 11, 181, DateTimeKind.Local).AddTicks(9375)
                        },
                        new
                        {
                            Id = 35,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 16, 16, 50, 41, 908, DateTimeKind.Local).AddTicks(1619),
                            DateShipped = new DateTime(2021, 7, 31, 21, 33, 58, 313, DateTimeKind.Local).AddTicks(9840)
                        },
                        new
                        {
                            Id = 36,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 8, 6, 10, 28, 41, 820, DateTimeKind.Local).AddTicks(1673),
                            DateShipped = new DateTime(2021, 6, 28, 20, 0, 58, 307, DateTimeKind.Local).AddTicks(2087)
                        },
                        new
                        {
                            Id = 37,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 20, 23, 31, 14, 616, DateTimeKind.Local).AddTicks(9261),
                            DateShipped = new DateTime(2021, 8, 10, 11, 34, 56, 430, DateTimeKind.Local).AddTicks(8461)
                        },
                        new
                        {
                            Id = 38,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 7, 18, 18, 30, 33, 235, DateTimeKind.Local).AddTicks(39),
                            DateShipped = new DateTime(2021, 11, 8, 10, 11, 31, 268, DateTimeKind.Local).AddTicks(5069)
                        },
                        new
                        {
                            Id = 39,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 7, 25, 15, 52, 51, 969, DateTimeKind.Local).AddTicks(3709),
                            DateShipped = new DateTime(2021, 12, 16, 3, 36, 19, 585, DateTimeKind.Local).AddTicks(9850)
                        },
                        new
                        {
                            Id = 40,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 9, 51, 43, 782, DateTimeKind.Local).AddTicks(4556),
                            DateShipped = new DateTime(2021, 6, 24, 0, 28, 9, 643, DateTimeKind.Local).AddTicks(156)
                        },
                        new
                        {
                            Id = 41,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 10, 19, 37, 58, DateTimeKind.Local).AddTicks(7234),
                            DateShipped = new DateTime(2021, 7, 20, 5, 45, 26, 898, DateTimeKind.Local).AddTicks(2029)
                        },
                        new
                        {
                            Id = 42,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 4, 44, 39, 597, DateTimeKind.Local).AddTicks(383),
                            DateShipped = new DateTime(2021, 8, 2, 1, 47, 36, 845, DateTimeKind.Local).AddTicks(7334)
                        },
                        new
                        {
                            Id = 43,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 25, 14, 13, 31, 363, DateTimeKind.Local).AddTicks(7562),
                            DateShipped = new DateTime(2021, 12, 1, 13, 31, 32, 606, DateTimeKind.Local).AddTicks(4929)
                        },
                        new
                        {
                            Id = 44,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 21, 8, 54, 301, DateTimeKind.Local).AddTicks(4140),
                            DateShipped = new DateTime(2021, 11, 21, 10, 0, 33, 168, DateTimeKind.Local).AddTicks(43)
                        },
                        new
                        {
                            Id = 45,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 6, 20, 18, 45, 0, 187, DateTimeKind.Local).AddTicks(6077),
                            DateShipped = new DateTime(2021, 6, 7, 0, 7, 19, 679, DateTimeKind.Local).AddTicks(9833)
                        },
                        new
                        {
                            Id = 46,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 6, 27, 16, 38, 54, 813, DateTimeKind.Local).AddTicks(5484),
                            DateShipped = new DateTime(2021, 5, 18, 3, 39, 48, 77, DateTimeKind.Local).AddTicks(6657)
                        },
                        new
                        {
                            Id = 47,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 14, 14, 37, 225, DateTimeKind.Local).AddTicks(4261),
                            DateShipped = new DateTime(2021, 10, 12, 10, 9, 14, 524, DateTimeKind.Local).AddTicks(7611)
                        },
                        new
                        {
                            Id = 48,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 5, 22, 28, 54, 841, DateTimeKind.Local).AddTicks(4401),
                            DateShipped = new DateTime(2021, 8, 19, 1, 15, 19, 372, DateTimeKind.Local).AddTicks(1319)
                        },
                        new
                        {
                            Id = 49,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 7, 28, 11, 38, 8, 149, DateTimeKind.Local).AddTicks(7242),
                            DateShipped = new DateTime(2021, 12, 11, 5, 26, 51, 671, DateTimeKind.Local).AddTicks(4708)
                        },
                        new
                        {
                            Id = 50,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 8, 10, 7, 38, 15, 671, DateTimeKind.Local).AddTicks(2537),
                            DateShipped = new DateTime(2021, 12, 21, 13, 22, 48, 222, DateTimeKind.Local).AddTicks(2296)
                        },
                        new
                        {
                            Id = 51,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 8, 7, 6, 39, 24, 598, DateTimeKind.Local).AddTicks(401),
                            DateShipped = new DateTime(2021, 9, 2, 3, 19, 15, 341, DateTimeKind.Local).AddTicks(6126)
                        },
                        new
                        {
                            Id = 52,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 10, 19, 6, 14, 34, 258, DateTimeKind.Local).AddTicks(8301),
                            DateShipped = new DateTime(2021, 6, 10, 8, 59, 8, 443, DateTimeKind.Local).AddTicks(6575)
                        },
                        new
                        {
                            Id = 53,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 8, 27, 11, 46, 55, 268, DateTimeKind.Local).AddTicks(5532),
                            DateShipped = new DateTime(2021, 6, 16, 7, 7, 23, 765, DateTimeKind.Local).AddTicks(2481)
                        },
                        new
                        {
                            Id = 54,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 7, 4, 10, 20, 19, 786, DateTimeKind.Local).AddTicks(9588),
                            DateShipped = new DateTime(2021, 5, 14, 21, 15, 37, 114, DateTimeKind.Local).AddTicks(1298)
                        },
                        new
                        {
                            Id = 55,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 5, 26, 4, 9, 34, 240, DateTimeKind.Local).AddTicks(757),
                            DateShipped = new DateTime(2021, 12, 16, 11, 31, 38, 326, DateTimeKind.Local).AddTicks(5660)
                        },
                        new
                        {
                            Id = 56,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 7, 25, 5, 17, 7, 975, DateTimeKind.Local).AddTicks(6876),
                            DateShipped = new DateTime(2021, 11, 9, 12, 29, 11, 530, DateTimeKind.Local).AddTicks(2671)
                        },
                        new
                        {
                            Id = 57,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 7, 17, 13, 4, 0, 733, DateTimeKind.Local).AddTicks(1597),
                            DateShipped = new DateTime(2021, 10, 7, 20, 1, 32, 406, DateTimeKind.Local).AddTicks(4221)
                        },
                        new
                        {
                            Id = 58,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 8, 23, 15, 32, 33, 896, DateTimeKind.Local).AddTicks(5265),
                            DateShipped = new DateTime(2021, 7, 17, 1, 28, 31, 659, DateTimeKind.Local).AddTicks(7892)
                        },
                        new
                        {
                            Id = 59,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 6, 23, 17, 32, 835, DateTimeKind.Local).AddTicks(908),
                            DateShipped = new DateTime(2021, 10, 30, 19, 0, 45, 113, DateTimeKind.Local).AddTicks(3171)
                        },
                        new
                        {
                            Id = 60,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 7, 11, 7, 1, 45, 481, DateTimeKind.Local).AddTicks(2895),
                            DateShipped = new DateTime(2021, 8, 25, 15, 38, 38, 136, DateTimeKind.Local).AddTicks(16)
                        },
                        new
                        {
                            Id = 61,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 11, 23, 33, 44, 646, DateTimeKind.Local).AddTicks(7761),
                            DateShipped = new DateTime(2021, 10, 29, 1, 1, 10, 168, DateTimeKind.Local).AddTicks(3447)
                        },
                        new
                        {
                            Id = 62,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 6, 30, 12, 47, 53, 358, DateTimeKind.Local).AddTicks(575),
                            DateShipped = new DateTime(2021, 8, 18, 21, 8, 22, 834, DateTimeKind.Local).AddTicks(6274)
                        },
                        new
                        {
                            Id = 63,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 21, 5, 6, 251, DateTimeKind.Local).AddTicks(4429),
                            DateShipped = new DateTime(2021, 11, 16, 3, 42, 0, 467, DateTimeKind.Local).AddTicks(9830)
                        },
                        new
                        {
                            Id = 64,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 6, 25, 20, 15, 28, 80, DateTimeKind.Local).AddTicks(6901),
                            DateShipped = new DateTime(2021, 11, 29, 18, 3, 23, 32, DateTimeKind.Local).AddTicks(989)
                        },
                        new
                        {
                            Id = 65,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 1, 3, 6, 2, 740, DateTimeKind.Local).AddTicks(2538),
                            DateShipped = new DateTime(2021, 9, 21, 5, 43, 3, 217, DateTimeKind.Local).AddTicks(6435)
                        },
                        new
                        {
                            Id = 66,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 5, 16, 18, 47, 29, 989, DateTimeKind.Local).AddTicks(8153),
                            DateShipped = new DateTime(2021, 8, 20, 10, 12, 47, 224, DateTimeKind.Local).AddTicks(5835)
                        },
                        new
                        {
                            Id = 67,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 30, 11, 59, 37, 437, DateTimeKind.Local).AddTicks(1461),
                            DateShipped = new DateTime(2021, 9, 10, 3, 26, 7, 782, DateTimeKind.Local).AddTicks(923)
                        },
                        new
                        {
                            Id = 68,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 8, 28, 12, 45, 4, 198, DateTimeKind.Local).AddTicks(5187),
                            DateShipped = new DateTime(2021, 6, 6, 18, 26, 29, 492, DateTimeKind.Local).AddTicks(7713)
                        },
                        new
                        {
                            Id = 69,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 5, 49, 49, 233, DateTimeKind.Local).AddTicks(5433),
                            DateShipped = new DateTime(2021, 5, 28, 10, 39, 20, 34, DateTimeKind.Local).AddTicks(8718)
                        },
                        new
                        {
                            Id = 70,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 6, 25, 17, 12, 16, 804, DateTimeKind.Local).AddTicks(7335),
                            DateShipped = new DateTime(2021, 12, 1, 21, 55, 38, 861, DateTimeKind.Local).AddTicks(8770)
                        },
                        new
                        {
                            Id = 71,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 4, 10, 7, 29, 148, DateTimeKind.Local).AddTicks(592),
                            DateShipped = new DateTime(2021, 7, 11, 17, 21, 51, 788, DateTimeKind.Local).AddTicks(4298)
                        },
                        new
                        {
                            Id = 72,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 7, 11, 12, 51, 25, 40, DateTimeKind.Local).AddTicks(2864),
                            DateShipped = new DateTime(2021, 11, 27, 21, 55, 7, 428, DateTimeKind.Local).AddTicks(939)
                        },
                        new
                        {
                            Id = 73,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 10, 55, 36, 573, DateTimeKind.Local).AddTicks(9147),
                            DateShipped = new DateTime(2021, 8, 14, 0, 19, 34, 577, DateTimeKind.Local).AddTicks(9321)
                        },
                        new
                        {
                            Id = 74,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 20, 15, 51, 19, 153, DateTimeKind.Local).AddTicks(9641),
                            DateShipped = new DateTime(2021, 5, 28, 13, 41, 4, 763, DateTimeKind.Local).AddTicks(9591)
                        },
                        new
                        {
                            Id = 75,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 7, 10, 1, 55, 11, 422, DateTimeKind.Local).AddTicks(6097),
                            DateShipped = new DateTime(2021, 8, 13, 3, 17, 0, 566, DateTimeKind.Local).AddTicks(7004)
                        },
                        new
                        {
                            Id = 76,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 2, 3, 17, 149, DateTimeKind.Local).AddTicks(2763),
                            DateShipped = new DateTime(2021, 12, 11, 23, 53, 13, 984, DateTimeKind.Local).AddTicks(1036)
                        },
                        new
                        {
                            Id = 77,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 7, 19, 21, 42, 4, 371, DateTimeKind.Local).AddTicks(166),
                            DateShipped = new DateTime(2021, 7, 6, 14, 59, 12, 152, DateTimeKind.Local).AddTicks(9773)
                        },
                        new
                        {
                            Id = 78,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 6, 24, 20, 24, 36, 592, DateTimeKind.Local).AddTicks(4022),
                            DateShipped = new DateTime(2021, 12, 6, 17, 18, 38, 634, DateTimeKind.Local).AddTicks(373)
                        },
                        new
                        {
                            Id = 79,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 6, 13, 9, 21, 36, 451, DateTimeKind.Local).AddTicks(7567),
                            DateShipped = new DateTime(2021, 11, 26, 5, 35, 4, 452, DateTimeKind.Local).AddTicks(4920)
                        },
                        new
                        {
                            Id = 80,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 6, 16, 3, 38, 27, 868, DateTimeKind.Local).AddTicks(225),
                            DateShipped = new DateTime(2021, 9, 4, 23, 43, 43, 460, DateTimeKind.Local).AddTicks(9688)
                        },
                        new
                        {
                            Id = 81,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 1, 18, 45, 10, 338, DateTimeKind.Local).AddTicks(2667),
                            DateShipped = new DateTime(2021, 7, 23, 4, 3, 1, 441, DateTimeKind.Local).AddTicks(441)
                        },
                        new
                        {
                            Id = 82,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 12, 11, 51, 43, 128, DateTimeKind.Local).AddTicks(1264),
                            DateShipped = new DateTime(2021, 5, 13, 13, 25, 22, 98, DateTimeKind.Local).AddTicks(9601)
                        },
                        new
                        {
                            Id = 83,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 3, 13, 15, 11, 60, DateTimeKind.Local).AddTicks(2338),
                            DateShipped = new DateTime(2021, 12, 30, 19, 51, 50, 278, DateTimeKind.Local).AddTicks(8185)
                        },
                        new
                        {
                            Id = 84,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 30, 1, 41, 14, 896, DateTimeKind.Local).AddTicks(6321),
                            DateShipped = new DateTime(2021, 6, 6, 0, 36, 11, 940, DateTimeKind.Local).AddTicks(562)
                        },
                        new
                        {
                            Id = 85,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 6, 18, 5, 4, 27, 277, DateTimeKind.Local).AddTicks(4562),
                            DateShipped = new DateTime(2021, 12, 3, 17, 16, 28, 171, DateTimeKind.Local).AddTicks(5657)
                        },
                        new
                        {
                            Id = 86,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 24, 19, 31, 43, 796, DateTimeKind.Local).AddTicks(8495),
                            DateShipped = new DateTime(2021, 7, 11, 15, 54, 5, 848, DateTimeKind.Local).AddTicks(874)
                        },
                        new
                        {
                            Id = 87,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 28, 14, 27, 12, 876, DateTimeKind.Local).AddTicks(4856),
                            DateShipped = new DateTime(2021, 11, 6, 18, 13, 27, 849, DateTimeKind.Local).AddTicks(2171)
                        },
                        new
                        {
                            Id = 88,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 7, 28, 18, 33, 50, 372, DateTimeKind.Local).AddTicks(5433),
                            DateShipped = new DateTime(2021, 11, 3, 20, 14, 1, 814, DateTimeKind.Local).AddTicks(7193)
                        },
                        new
                        {
                            Id = 89,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 17, 17, 49, 364, DateTimeKind.Local).AddTicks(772),
                            DateShipped = new DateTime(2021, 12, 25, 5, 26, 55, 505, DateTimeKind.Local).AddTicks(9117)
                        },
                        new
                        {
                            Id = 90,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 8, 4, 17, 45, 736, DateTimeKind.Local).AddTicks(7981),
                            DateShipped = new DateTime(2021, 12, 23, 16, 19, 53, 392, DateTimeKind.Local).AddTicks(2594)
                        },
                        new
                        {
                            Id = 91,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 4, 3, 37, 52, 264, DateTimeKind.Local).AddTicks(2474),
                            DateShipped = new DateTime(2021, 12, 5, 22, 2, 28, 564, DateTimeKind.Local).AddTicks(3408)
                        },
                        new
                        {
                            Id = 92,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 1, 22, 10, 1, 974, DateTimeKind.Local).AddTicks(3565),
                            DateShipped = new DateTime(2021, 6, 15, 20, 57, 15, 896, DateTimeKind.Local).AddTicks(7405)
                        },
                        new
                        {
                            Id = 93,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 5, 28, 13, 23, 38, 624, DateTimeKind.Local).AddTicks(2014),
                            DateShipped = new DateTime(2021, 8, 18, 17, 53, 38, 302, DateTimeKind.Local).AddTicks(1222)
                        },
                        new
                        {
                            Id = 94,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 6, 30, 11, 51, 9, 896, DateTimeKind.Local).AddTicks(5296),
                            DateShipped = new DateTime(2021, 8, 13, 3, 23, 19, 135, DateTimeKind.Local).AddTicks(4817)
                        },
                        new
                        {
                            Id = 95,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 22, 8, 12, 35, 3, DateTimeKind.Local).AddTicks(7638),
                            DateShipped = new DateTime(2021, 11, 8, 6, 2, 21, 567, DateTimeKind.Local).AddTicks(5205)
                        },
                        new
                        {
                            Id = 96,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 5, 30, 15, 56, 23, 234, DateTimeKind.Local).AddTicks(6981),
                            DateShipped = new DateTime(2021, 5, 15, 21, 57, 20, 540, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            Id = 97,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 29, 13, 46, 22, 567, DateTimeKind.Local).AddTicks(8130),
                            DateShipped = new DateTime(2021, 11, 2, 11, 36, 20, 111, DateTimeKind.Local).AddTicks(2962)
                        },
                        new
                        {
                            Id = 98,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 5, 18, 56, 9, 839, DateTimeKind.Local).AddTicks(5909),
                            DateShipped = new DateTime(2021, 7, 14, 12, 34, 17, 318, DateTimeKind.Local).AddTicks(1268)
                        },
                        new
                        {
                            Id = 99,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 8, 22, 14, 59, 46, 678, DateTimeKind.Local).AddTicks(2017),
                            DateShipped = new DateTime(2021, 7, 13, 20, 2, 41, 573, DateTimeKind.Local).AddTicks(5216)
                        },
                        new
                        {
                            Id = 100,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 8, 4, 5, 39, 21, 185, DateTimeKind.Local).AddTicks(2374),
                            DateShipped = new DateTime(2021, 12, 8, 14, 1, 58, 614, DateTimeKind.Local).AddTicks(8630)
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.HasOne("EPManifest.Core.Manifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.HasOne("EPManifest.Core.Carrier", "Carrier")
                        .WithMany("Manifests")
                        .HasForeignKey("CarrierId");

                    b.HasOne("EPManifest.Core.Consignee", "Consignee")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsigneeId");

                    b.HasOne("EPManifest.Core.Consignor", "Consignor")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsignorId");

                    b.OwnsOne("EPManifest.Core.Address", "ConsigneeAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsigneeAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.OwnsOne("EPManifest.Core.Address", "ConsignorAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsignorAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeAddress");

                    b.Navigation("Consignor");

                    b.Navigation("ConsignorAddress");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
