// <auto-generated />
using System;
using EPManifest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPManifest.Data.Migrations
{
    [DbContext(typeof(EPManifestDbContext))]
    [Migration("20210512080627_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1 Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pacific Northwest Freight"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AP Freight"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NM Shipping Inc"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Frank's Freight"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pete's Disposal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATI Environmental"
                        },
                        new
                        {
                            Id = 3,
                            Name = "EQ Enviro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Whitehorse Landfill"
                        },
                        new
                        {
                            Id = 5,
                            Name = "YAE"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consignors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carmacks Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mayo Health Centre"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whitehorse General Hospital"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Teslin Health Centre"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Whistle Bend Place"
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsignorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateShipped")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("ConsignorId");

                    b.ToTable("Manifests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 25, 22, 59, 44, 13, DateTimeKind.Unspecified).AddTicks(8985),
                            DateShipped = new DateTime(2021, 6, 3, 6, 13, 27, 787, DateTimeKind.Unspecified).AddTicks(2604)
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 13, 47, 13, 846, DateTimeKind.Unspecified).AddTicks(1958),
                            DateShipped = new DateTime(2021, 8, 8, 18, 24, 55, 613, DateTimeKind.Unspecified).AddTicks(1216)
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 14, 0, 3, 21, 911, DateTimeKind.Unspecified).AddTicks(1157),
                            DateShipped = new DateTime(2021, 8, 6, 8, 35, 53, 733, DateTimeKind.Unspecified).AddTicks(1457)
                        },
                        new
                        {
                            Id = 4,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 7, 12, 23, 16, 131, DateTimeKind.Unspecified).AddTicks(1324),
                            DateShipped = new DateTime(2021, 8, 14, 16, 56, 15, 104, DateTimeKind.Unspecified).AddTicks(5809)
                        },
                        new
                        {
                            Id = 5,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 0, 29, 43, 864, DateTimeKind.Unspecified).AddTicks(7165),
                            DateShipped = new DateTime(2021, 6, 27, 12, 44, 38, 777, DateTimeKind.Unspecified).AddTicks(1230)
                        },
                        new
                        {
                            Id = 6,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 15, 5, 45, 493, DateTimeKind.Unspecified).AddTicks(5446),
                            DateShipped = new DateTime(2021, 5, 26, 3, 24, 6, 884, DateTimeKind.Unspecified).AddTicks(4530)
                        },
                        new
                        {
                            Id = 7,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 20, 17, 8, 2, 18, DateTimeKind.Unspecified).AddTicks(5502),
                            DateShipped = new DateTime(2021, 7, 26, 13, 5, 3, 103, DateTimeKind.Unspecified).AddTicks(919)
                        },
                        new
                        {
                            Id = 8,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 4, 18, 44, 45, 259, DateTimeKind.Unspecified).AddTicks(8579),
                            DateShipped = new DateTime(2021, 7, 8, 1, 45, 57, 665, DateTimeKind.Unspecified).AddTicks(9009)
                        },
                        new
                        {
                            Id = 9,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 13, 22, 56, 22, 177, DateTimeKind.Unspecified).AddTicks(933),
                            DateShipped = new DateTime(2021, 5, 15, 15, 24, 27, 579, DateTimeKind.Unspecified).AddTicks(5128)
                        },
                        new
                        {
                            Id = 10,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 27, 20, 21, 20, 152, DateTimeKind.Unspecified).AddTicks(4280),
                            DateShipped = new DateTime(2021, 7, 1, 4, 11, 27, 462, DateTimeKind.Unspecified).AddTicks(2072)
                        },
                        new
                        {
                            Id = 11,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 11, 20, 6, 45, 489, DateTimeKind.Unspecified).AddTicks(2177),
                            DateShipped = new DateTime(2021, 6, 23, 23, 55, 31, 257, DateTimeKind.Unspecified).AddTicks(9854)
                        },
                        new
                        {
                            Id = 12,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 7, 44, 49, 858, DateTimeKind.Unspecified).AddTicks(8757),
                            DateShipped = new DateTime(2021, 6, 27, 0, 0, 4, 940, DateTimeKind.Unspecified).AddTicks(6290)
                        },
                        new
                        {
                            Id = 13,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 7, 9, 21, 46, 569, DateTimeKind.Unspecified).AddTicks(5934),
                            DateShipped = new DateTime(2021, 5, 15, 13, 59, 7, 416, DateTimeKind.Unspecified).AddTicks(7775)
                        },
                        new
                        {
                            Id = 14,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 3, 0, 40, 58, 331, DateTimeKind.Unspecified).AddTicks(7887),
                            DateShipped = new DateTime(2021, 6, 20, 2, 37, 40, 905, DateTimeKind.Unspecified).AddTicks(5980)
                        },
                        new
                        {
                            Id = 15,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 13, 43, 54, 572, DateTimeKind.Unspecified).AddTicks(1609),
                            DateShipped = new DateTime(2021, 6, 14, 3, 17, 11, 262, DateTimeKind.Unspecified).AddTicks(5672)
                        },
                        new
                        {
                            Id = 16,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 13, 22, 59, 28, 269, DateTimeKind.Unspecified).AddTicks(2645),
                            DateShipped = new DateTime(2021, 6, 15, 5, 13, 23, 154, DateTimeKind.Unspecified).AddTicks(2657)
                        },
                        new
                        {
                            Id = 17,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 12, 5, 4, 51, 196, DateTimeKind.Unspecified).AddTicks(3503),
                            DateShipped = new DateTime(2021, 5, 29, 3, 17, 43, 268, DateTimeKind.Unspecified).AddTicks(5091)
                        },
                        new
                        {
                            Id = 18,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 22, 29, 38, 708, DateTimeKind.Unspecified).AddTicks(3809),
                            DateShipped = new DateTime(2021, 6, 17, 17, 34, 19, 869, DateTimeKind.Unspecified).AddTicks(5379)
                        },
                        new
                        {
                            Id = 19,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 10, 6, 22, 51, 208, DateTimeKind.Unspecified).AddTicks(2240),
                            DateShipped = new DateTime(2021, 6, 13, 1, 20, 42, 510, DateTimeKind.Unspecified).AddTicks(7710)
                        },
                        new
                        {
                            Id = 20,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 2, 14, 2, 9, 653, DateTimeKind.Unspecified).AddTicks(4073),
                            DateShipped = new DateTime(2021, 6, 7, 1, 56, 49, 269, DateTimeKind.Unspecified).AddTicks(5686)
                        },
                        new
                        {
                            Id = 21,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 26, 21, 56, 52, 83, DateTimeKind.Unspecified).AddTicks(785),
                            DateShipped = new DateTime(2021, 7, 27, 18, 13, 10, 700, DateTimeKind.Unspecified).AddTicks(5899)
                        },
                        new
                        {
                            Id = 22,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 29, 12, 45, 31, 294, DateTimeKind.Unspecified).AddTicks(7621),
                            DateShipped = new DateTime(2021, 5, 29, 17, 48, 59, 722, DateTimeKind.Unspecified).AddTicks(4606)
                        },
                        new
                        {
                            Id = 23,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 30, 4, 56, 29, 856, DateTimeKind.Unspecified).AddTicks(9250),
                            DateShipped = new DateTime(2021, 6, 14, 16, 25, 52, 453, DateTimeKind.Unspecified).AddTicks(3115)
                        },
                        new
                        {
                            Id = 24,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 24, 7, 7, 40, 565, DateTimeKind.Unspecified).AddTicks(6356),
                            DateShipped = new DateTime(2021, 6, 2, 10, 32, 41, 569, DateTimeKind.Unspecified).AddTicks(65)
                        },
                        new
                        {
                            Id = 25,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 19, 15, 53, 48, 886, DateTimeKind.Unspecified).AddTicks(334),
                            DateShipped = new DateTime(2021, 7, 8, 5, 26, 51, 719, DateTimeKind.Unspecified).AddTicks(9468)
                        },
                        new
                        {
                            Id = 26,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 3, 21, 13, 304, DateTimeKind.Unspecified).AddTicks(2237),
                            DateShipped = new DateTime(2021, 8, 1, 8, 31, 39, 948, DateTimeKind.Unspecified).AddTicks(9659)
                        },
                        new
                        {
                            Id = 27,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 8, 10, 58, 40, 332, DateTimeKind.Unspecified).AddTicks(8719),
                            DateShipped = new DateTime(2021, 6, 13, 17, 4, 23, 401, DateTimeKind.Unspecified).AddTicks(273)
                        },
                        new
                        {
                            Id = 28,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 5, 4, 2, 16, 347, DateTimeKind.Unspecified).AddTicks(1918),
                            DateShipped = new DateTime(2021, 6, 2, 0, 29, 7, 652, DateTimeKind.Unspecified).AddTicks(3601)
                        },
                        new
                        {
                            Id = 29,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 7, 37, 35, 107, DateTimeKind.Unspecified).AddTicks(594),
                            DateShipped = new DateTime(2021, 6, 19, 3, 3, 57, 564, DateTimeKind.Unspecified).AddTicks(5987)
                        },
                        new
                        {
                            Id = 30,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 13, 13, 55, 26, 950, DateTimeKind.Unspecified).AddTicks(1398),
                            DateShipped = new DateTime(2021, 5, 16, 7, 9, 39, 423, DateTimeKind.Unspecified).AddTicks(6109)
                        },
                        new
                        {
                            Id = 31,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 27, 18, 42, 37, 571, DateTimeKind.Unspecified).AddTicks(6750),
                            DateShipped = new DateTime(2021, 5, 15, 22, 32, 39, 971, DateTimeKind.Unspecified).AddTicks(6505)
                        },
                        new
                        {
                            Id = 32,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 3, 29, 52, 157, DateTimeKind.Unspecified).AddTicks(1731),
                            DateShipped = new DateTime(2021, 6, 11, 12, 14, 5, 891, DateTimeKind.Unspecified).AddTicks(5498)
                        },
                        new
                        {
                            Id = 33,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 30, 13, 38, 43, 263, DateTimeKind.Unspecified).AddTicks(7709),
                            DateShipped = new DateTime(2021, 8, 17, 10, 39, 44, 102, DateTimeKind.Unspecified).AddTicks(7439)
                        },
                        new
                        {
                            Id = 34,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 11, 13, 52, 39, 816, DateTimeKind.Unspecified).AddTicks(4255),
                            DateShipped = new DateTime(2021, 8, 3, 14, 55, 24, 37, DateTimeKind.Unspecified).AddTicks(7721)
                        },
                        new
                        {
                            Id = 35,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 11, 9, 40, 28, 575, DateTimeKind.Unspecified).AddTicks(2965),
                            DateShipped = new DateTime(2021, 6, 26, 23, 45, 54, 296, DateTimeKind.Unspecified).AddTicks(8821)
                        },
                        new
                        {
                            Id = 36,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 18, 18, 47, 16, 498, DateTimeKind.Unspecified).AddTicks(4261),
                            DateShipped = new DateTime(2021, 7, 16, 11, 29, 19, 345, DateTimeKind.Unspecified).AddTicks(4688)
                        },
                        new
                        {
                            Id = 37,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 14, 6, 29, 23, 162, DateTimeKind.Unspecified).AddTicks(3243),
                            DateShipped = new DateTime(2021, 8, 17, 21, 52, 21, 277, DateTimeKind.Unspecified).AddTicks(3454)
                        },
                        new
                        {
                            Id = 38,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 4, 2, 37, 38, 964, DateTimeKind.Unspecified).AddTicks(5102),
                            DateShipped = new DateTime(2021, 6, 16, 18, 31, 48, 684, DateTimeKind.Unspecified).AddTicks(1462)
                        },
                        new
                        {
                            Id = 39,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 28, 22, 42, 14, 500, DateTimeKind.Unspecified).AddTicks(6206),
                            DateShipped = new DateTime(2021, 6, 10, 10, 27, 1, 221, DateTimeKind.Unspecified).AddTicks(9890)
                        },
                        new
                        {
                            Id = 40,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 10, 9, 29, 11, 172, DateTimeKind.Unspecified).AddTicks(906),
                            DateShipped = new DateTime(2021, 5, 22, 0, 36, 34, 793, DateTimeKind.Unspecified).AddTicks(2462)
                        },
                        new
                        {
                            Id = 41,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 20, 2, 15, 2, 117, DateTimeKind.Unspecified).AddTicks(7955),
                            DateShipped = new DateTime(2021, 7, 31, 17, 34, 28, 854, DateTimeKind.Unspecified).AddTicks(2810)
                        },
                        new
                        {
                            Id = 42,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 9, 7, 20, 40, 39, 690, DateTimeKind.Unspecified).AddTicks(136),
                            DateShipped = new DateTime(2021, 6, 3, 13, 32, 52, 482, DateTimeKind.Unspecified).AddTicks(7323)
                        },
                        new
                        {
                            Id = 43,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 29, 15, 33, 37, 416, DateTimeKind.Unspecified).AddTicks(4422),
                            DateShipped = new DateTime(2021, 5, 25, 14, 36, 36, 326, DateTimeKind.Unspecified).AddTicks(9300)
                        },
                        new
                        {
                            Id = 44,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 8, 38, 10, 694, DateTimeKind.Unspecified).AddTicks(7042),
                            DateShipped = new DateTime(2021, 5, 10, 8, 15, 46, 386, DateTimeKind.Unspecified).AddTicks(4852)
                        },
                        new
                        {
                            Id = 45,
                            CarrierId = 2,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 20, 6, 25, 48, 973, DateTimeKind.Unspecified).AddTicks(7052),
                            DateShipped = new DateTime(2021, 6, 3, 16, 35, 29, 154, DateTimeKind.Unspecified).AddTicks(1467)
                        },
                        new
                        {
                            Id = 46,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 18, 5, 20, 242, DateTimeKind.Unspecified).AddTicks(1879),
                            DateShipped = new DateTime(2021, 7, 27, 10, 54, 50, 928, DateTimeKind.Unspecified).AddTicks(5237)
                        },
                        new
                        {
                            Id = 47,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 19, 22, 3, 33, 846, DateTimeKind.Unspecified).AddTicks(7413),
                            DateShipped = new DateTime(2021, 7, 7, 13, 11, 0, 297, DateTimeKind.Unspecified).AddTicks(6141)
                        },
                        new
                        {
                            Id = 48,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 15, 23, 43, 13, 892, DateTimeKind.Unspecified).AddTicks(5217),
                            DateShipped = new DateTime(2021, 6, 2, 18, 56, 24, 719, DateTimeKind.Unspecified).AddTicks(1100)
                        },
                        new
                        {
                            Id = 49,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 6, 9, 9, 13, 563, DateTimeKind.Unspecified).AddTicks(7398),
                            DateShipped = new DateTime(2021, 6, 10, 6, 1, 6, 3, DateTimeKind.Unspecified).AddTicks(5547)
                        },
                        new
                        {
                            Id = 50,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 23, 15, 26, 7, 444, DateTimeKind.Unspecified).AddTicks(6722),
                            DateShipped = new DateTime(2021, 6, 11, 17, 16, 52, 933, DateTimeKind.Unspecified).AddTicks(6349)
                        },
                        new
                        {
                            Id = 51,
                            CarrierId = 3,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 21, 11, 25, 44, 685, DateTimeKind.Unspecified).AddTicks(7599),
                            DateShipped = new DateTime(2021, 6, 10, 15, 24, 35, 537, DateTimeKind.Unspecified).AddTicks(9488)
                        },
                        new
                        {
                            Id = 52,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 14, 20, 58, 674, DateTimeKind.Unspecified).AddTicks(8036),
                            DateShipped = new DateTime(2021, 8, 10, 22, 22, 20, 490, DateTimeKind.Unspecified).AddTicks(8421)
                        },
                        new
                        {
                            Id = 53,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 9, 23, 3, 36, 669, DateTimeKind.Unspecified).AddTicks(3657),
                            DateShipped = new DateTime(2021, 6, 26, 14, 36, 13, 905, DateTimeKind.Unspecified).AddTicks(4463)
                        },
                        new
                        {
                            Id = 54,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 13, 3, 43, 56, 828, DateTimeKind.Unspecified).AddTicks(9146),
                            DateShipped = new DateTime(2021, 8, 2, 2, 46, 6, 637, DateTimeKind.Unspecified).AddTicks(8783)
                        },
                        new
                        {
                            Id = 55,
                            CarrierId = 1,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 22, 15, 24, 37, 372, DateTimeKind.Unspecified).AddTicks(4188),
                            DateShipped = new DateTime(2021, 6, 22, 2, 58, 29, 215, DateTimeKind.Unspecified).AddTicks(9068)
                        },
                        new
                        {
                            Id = 56,
                            CarrierId = 5,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 30, 10, 17, 28, 698, DateTimeKind.Unspecified).AddTicks(2786),
                            DateShipped = new DateTime(2021, 7, 25, 14, 26, 13, 287, DateTimeKind.Unspecified).AddTicks(7824)
                        },
                        new
                        {
                            Id = 57,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 26, 3, 0, 32, 255, DateTimeKind.Unspecified).AddTicks(6337),
                            DateShipped = new DateTime(2021, 7, 5, 22, 25, 33, 439, DateTimeKind.Unspecified).AddTicks(7856)
                        },
                        new
                        {
                            Id = 58,
                            CarrierId = 5,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 17, 22, 54, 2, 796, DateTimeKind.Unspecified).AddTicks(3164),
                            DateShipped = new DateTime(2021, 7, 16, 14, 25, 12, 868, DateTimeKind.Unspecified).AddTicks(9993)
                        },
                        new
                        {
                            Id = 59,
                            CarrierId = 2,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 18, 15, 4, 25, 265, DateTimeKind.Unspecified).AddTicks(8969),
                            DateShipped = new DateTime(2021, 6, 22, 4, 18, 37, 383, DateTimeKind.Unspecified).AddTicks(5529)
                        },
                        new
                        {
                            Id = 60,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 9, 7, 11, 27, 30, 716, DateTimeKind.Unspecified).AddTicks(4864),
                            DateShipped = new DateTime(2021, 6, 1, 17, 37, 20, 243, DateTimeKind.Unspecified).AddTicks(4138)
                        },
                        new
                        {
                            Id = 61,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 19, 13, 13, 44, 867, DateTimeKind.Unspecified).AddTicks(9949),
                            DateShipped = new DateTime(2021, 7, 27, 4, 36, 36, 112, DateTimeKind.Unspecified).AddTicks(7656)
                        },
                        new
                        {
                            Id = 62,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 3, 11, 10, 14, 907, DateTimeKind.Unspecified).AddTicks(9421),
                            DateShipped = new DateTime(2021, 7, 17, 2, 21, 1, 506, DateTimeKind.Unspecified).AddTicks(3111)
                        },
                        new
                        {
                            Id = 63,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 6, 23, 41, 55, 809, DateTimeKind.Unspecified).AddTicks(1391),
                            DateShipped = new DateTime(2021, 5, 16, 23, 41, 55, 694, DateTimeKind.Unspecified).AddTicks(9575)
                        },
                        new
                        {
                            Id = 64,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 10, 27, 49, 123, DateTimeKind.Unspecified).AddTicks(3587),
                            DateShipped = new DateTime(2021, 6, 2, 17, 29, 46, 224, DateTimeKind.Unspecified).AddTicks(4721)
                        },
                        new
                        {
                            Id = 65,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 9, 5, 56, 33, 717, DateTimeKind.Unspecified).AddTicks(2423),
                            DateShipped = new DateTime(2021, 5, 20, 0, 38, 22, 823, DateTimeKind.Unspecified).AddTicks(1974)
                        },
                        new
                        {
                            Id = 66,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 5, 7, 57, 49, 410, DateTimeKind.Unspecified).AddTicks(9946),
                            DateShipped = new DateTime(2021, 8, 1, 9, 28, 29, 996, DateTimeKind.Unspecified).AddTicks(2527)
                        },
                        new
                        {
                            Id = 67,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 29, 23, 19, 29, 229, DateTimeKind.Unspecified).AddTicks(757),
                            DateShipped = new DateTime(2021, 7, 19, 10, 41, 13, 846, DateTimeKind.Unspecified).AddTicks(4937)
                        },
                        new
                        {
                            Id = 68,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 12, 22, 10, 44, 48, 534, DateTimeKind.Unspecified).AddTicks(2450),
                            DateShipped = new DateTime(2021, 5, 20, 18, 58, 36, 416, DateTimeKind.Unspecified).AddTicks(4846)
                        },
                        new
                        {
                            Id = 69,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 8, 17, 18, 45, 824, DateTimeKind.Unspecified).AddTicks(7547),
                            DateShipped = new DateTime(2021, 5, 17, 6, 46, 42, 832, DateTimeKind.Unspecified).AddTicks(5254)
                        },
                        new
                        {
                            Id = 70,
                            CarrierId = 2,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 1, 14, 10, 580, DateTimeKind.Unspecified).AddTicks(1266),
                            DateShipped = new DateTime(2021, 7, 15, 0, 2, 4, 672, DateTimeKind.Unspecified).AddTicks(3876)
                        },
                        new
                        {
                            Id = 71,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 31, 1, 38, 31, 32, DateTimeKind.Unspecified).AddTicks(7167),
                            DateShipped = new DateTime(2021, 7, 3, 15, 12, 52, 894, DateTimeKind.Unspecified).AddTicks(7671)
                        },
                        new
                        {
                            Id = 72,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 15, 1, 5, 45, 395, DateTimeKind.Unspecified).AddTicks(3389),
                            DateShipped = new DateTime(2021, 5, 22, 9, 4, 39, 769, DateTimeKind.Unspecified).AddTicks(9320)
                        },
                        new
                        {
                            Id = 73,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 18, 22, 5, 8, 75, DateTimeKind.Unspecified).AddTicks(4799),
                            DateShipped = new DateTime(2021, 7, 12, 23, 32, 30, 909, DateTimeKind.Unspecified).AddTicks(848)
                        },
                        new
                        {
                            Id = 74,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 4, 20, 46, 38, 761, DateTimeKind.Unspecified).AddTicks(495),
                            DateShipped = new DateTime(2021, 6, 15, 11, 26, 52, 708, DateTimeKind.Unspecified).AddTicks(6459)
                        },
                        new
                        {
                            Id = 75,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 12, 21, 18, 43, 35, 500, DateTimeKind.Unspecified).AddTicks(5098),
                            DateShipped = new DateTime(2021, 6, 10, 20, 34, 17, 452, DateTimeKind.Unspecified).AddTicks(2557)
                        },
                        new
                        {
                            Id = 76,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 28, 11, 46, 26, 68, DateTimeKind.Unspecified).AddTicks(6872),
                            DateShipped = new DateTime(2021, 7, 8, 17, 6, 39, 766, DateTimeKind.Unspecified).AddTicks(6124)
                        },
                        new
                        {
                            Id = 77,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 10, 21, 21, 2, 57, 837, DateTimeKind.Unspecified).AddTicks(2924),
                            DateShipped = new DateTime(2021, 7, 18, 2, 9, 4, 568, DateTimeKind.Unspecified).AddTicks(8597)
                        },
                        new
                        {
                            Id = 78,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 12, 4, 55, 48, 979, DateTimeKind.Unspecified).AddTicks(7377),
                            DateShipped = new DateTime(2021, 5, 23, 8, 31, 53, 774, DateTimeKind.Unspecified).AddTicks(770)
                        },
                        new
                        {
                            Id = 79,
                            CarrierId = 4,
                            ConsigneeId = 3,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 12, 51, 31, 252, DateTimeKind.Unspecified).AddTicks(2144),
                            DateShipped = new DateTime(2021, 6, 4, 22, 53, 37, 900, DateTimeKind.Unspecified).AddTicks(2535)
                        },
                        new
                        {
                            Id = 80,
                            CarrierId = 4,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 10, 8, 6, 1, 5, 779, DateTimeKind.Unspecified).AddTicks(7378),
                            DateShipped = new DateTime(2021, 6, 26, 6, 36, 52, 512, DateTimeKind.Unspecified).AddTicks(8544)
                        },
                        new
                        {
                            Id = 81,
                            CarrierId = 5,
                            ConsigneeId = 2,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 30, 17, 29, 42, 812, DateTimeKind.Unspecified).AddTicks(7424),
                            DateShipped = new DateTime(2021, 5, 14, 8, 27, 9, 982, DateTimeKind.Unspecified).AddTicks(1340)
                        },
                        new
                        {
                            Id = 82,
                            CarrierId = 2,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 27, 7, 16, 55, 253, DateTimeKind.Unspecified).AddTicks(9167),
                            DateShipped = new DateTime(2021, 7, 12, 9, 30, 57, 336, DateTimeKind.Unspecified).AddTicks(4313)
                        },
                        new
                        {
                            Id = 83,
                            CarrierId = 3,
                            ConsigneeId = 5,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 12, 2, 4, 54, 23, 23, DateTimeKind.Unspecified).AddTicks(8168),
                            DateShipped = new DateTime(2021, 5, 24, 18, 19, 2, 597, DateTimeKind.Unspecified).AddTicks(2128)
                        },
                        new
                        {
                            Id = 84,
                            CarrierId = 4,
                            ConsigneeId = 4,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 11, 10, 9, 46, 9, 957, DateTimeKind.Unspecified).AddTicks(5126),
                            DateShipped = new DateTime(2021, 5, 25, 15, 2, 25, 526, DateTimeKind.Unspecified).AddTicks(5342)
                        },
                        new
                        {
                            Id = 85,
                            CarrierId = 1,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 13, 1, 38, 14, 137, DateTimeKind.Unspecified).AddTicks(2944),
                            DateShipped = new DateTime(2021, 6, 4, 19, 51, 11, 116, DateTimeKind.Unspecified).AddTicks(3332)
                        },
                        new
                        {
                            Id = 86,
                            CarrierId = 2,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 30, 0, 34, 13, 409, DateTimeKind.Unspecified).AddTicks(4224),
                            DateShipped = new DateTime(2021, 7, 20, 6, 22, 1, 138, DateTimeKind.Unspecified).AddTicks(1676)
                        },
                        new
                        {
                            Id = 87,
                            CarrierId = 5,
                            ConsigneeId = 3,
                            ConsignorId = 3,
                            DateScheduledArrival = new DateTime(2021, 9, 16, 11, 24, 9, 865, DateTimeKind.Unspecified).AddTicks(7552),
                            DateShipped = new DateTime(2021, 6, 3, 7, 25, 27, 331, DateTimeKind.Unspecified).AddTicks(3244)
                        },
                        new
                        {
                            Id = 88,
                            CarrierId = 1,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 9, 2, 26, 41, 762, DateTimeKind.Unspecified).AddTicks(396),
                            DateShipped = new DateTime(2021, 7, 18, 8, 20, 0, 573, DateTimeKind.Unspecified).AddTicks(2780)
                        },
                        new
                        {
                            Id = 89,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 11, 12, 4, 37, 57, 166, DateTimeKind.Unspecified).AddTicks(1985),
                            DateShipped = new DateTime(2021, 6, 24, 9, 8, 52, 334, DateTimeKind.Unspecified).AddTicks(4041)
                        },
                        new
                        {
                            Id = 90,
                            CarrierId = 3,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 9, 20, 15, 51, 12, 141, DateTimeKind.Unspecified).AddTicks(376),
                            DateShipped = new DateTime(2021, 7, 2, 7, 43, 6, 100, DateTimeKind.Unspecified).AddTicks(7581)
                        },
                        new
                        {
                            Id = 91,
                            CarrierId = 3,
                            ConsigneeId = 3,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 9, 27, 15, 27, 13, 623, DateTimeKind.Unspecified).AddTicks(3920),
                            DateShipped = new DateTime(2021, 8, 13, 8, 38, 7, 346, DateTimeKind.Unspecified).AddTicks(6234)
                        },
                        new
                        {
                            Id = 92,
                            CarrierId = 4,
                            ConsigneeId = 1,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 10, 9, 18, 50, 11, 824, DateTimeKind.Unspecified).AddTicks(8138),
                            DateShipped = new DateTime(2021, 6, 28, 21, 46, 21, 835, DateTimeKind.Unspecified).AddTicks(1187)
                        },
                        new
                        {
                            Id = 93,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 9, 4, 21, 38, 987, DateTimeKind.Unspecified).AddTicks(1948),
                            DateShipped = new DateTime(2021, 7, 13, 7, 47, 1, 451, DateTimeKind.Unspecified).AddTicks(4431)
                        },
                        new
                        {
                            Id = 94,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 17, 7, 55, 56, 406, DateTimeKind.Unspecified).AddTicks(4174),
                            DateShipped = new DateTime(2021, 5, 10, 1, 19, 52, 724, DateTimeKind.Unspecified).AddTicks(8009)
                        },
                        new
                        {
                            Id = 95,
                            CarrierId = 1,
                            ConsigneeId = 4,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 11, 24, 22, 48, 40, 987, DateTimeKind.Unspecified).AddTicks(4804),
                            DateShipped = new DateTime(2021, 5, 17, 22, 14, 14, 595, DateTimeKind.Unspecified).AddTicks(6701)
                        },
                        new
                        {
                            Id = 96,
                            CarrierId = 4,
                            ConsigneeId = 5,
                            ConsignorId = 2,
                            DateScheduledArrival = new DateTime(2021, 11, 19, 4, 43, 55, 3, DateTimeKind.Unspecified).AddTicks(2036),
                            DateShipped = new DateTime(2021, 7, 21, 5, 8, 10, 338, DateTimeKind.Unspecified).AddTicks(5412)
                        },
                        new
                        {
                            Id = 97,
                            CarrierId = 5,
                            ConsigneeId = 1,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 12, 10, 17, 54, 3, 809, DateTimeKind.Unspecified).AddTicks(6466),
                            DateShipped = new DateTime(2021, 7, 1, 13, 54, 40, 673, DateTimeKind.Unspecified).AddTicks(5451)
                        },
                        new
                        {
                            Id = 98,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 5,
                            DateScheduledArrival = new DateTime(2021, 12, 8, 9, 8, 9, 962, DateTimeKind.Unspecified).AddTicks(8375),
                            DateShipped = new DateTime(2021, 5, 8, 23, 40, 44, 135, DateTimeKind.Unspecified).AddTicks(5387)
                        },
                        new
                        {
                            Id = 99,
                            CarrierId = 3,
                            ConsigneeId = 2,
                            ConsignorId = 4,
                            DateScheduledArrival = new DateTime(2021, 10, 10, 23, 0, 34, 662, DateTimeKind.Unspecified).AddTicks(5878),
                            DateShipped = new DateTime(2021, 6, 11, 11, 39, 14, 624, DateTimeKind.Unspecified).AddTicks(749)
                        },
                        new
                        {
                            Id = 100,
                            CarrierId = 1,
                            ConsigneeId = 1,
                            ConsignorId = 1,
                            DateScheduledArrival = new DateTime(2021, 11, 16, 10, 7, 4, 395, DateTimeKind.Unspecified).AddTicks(6899),
                            DateShipped = new DateTime(2021, 5, 19, 2, 13, 35, 115, DateTimeKind.Unspecified).AddTicks(1694)
                        });
                });

            modelBuilder.Entity("EPManifest.Core.Item", b =>
                {
                    b.HasOne("EPManifest.Core.Manifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.HasOne("EPManifest.Core.Carrier", "Carrier")
                        .WithMany("Manifests")
                        .HasForeignKey("CarrierId");

                    b.HasOne("EPManifest.Core.Consignee", "Consignee")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsigneeId");

                    b.HasOne("EPManifest.Core.Consignor", "Consignor")
                        .WithMany("Manifests")
                        .HasForeignKey("ConsignorId");

                    b.OwnsOne("EPManifest.Core.Address", "ConsigneeAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsigneeAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.OwnsOne("EPManifest.Core.Address", "ConsignorAddress", b1 =>
                        {
                            b1.Property<int>("ManifestId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(7)
                                .IsUnicode(false)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.HasKey("ManifestId");

                            b1.ToTable("ConsignorAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ManifestId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("Consignee");

                    b.Navigation("ConsigneeAddress");

                    b.Navigation("Consignor");

                    b.Navigation("ConsignorAddress");
                });

            modelBuilder.Entity("EPManifest.Core.Carrier", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignee", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Consignor", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("EPManifest.Core.Manifest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
